// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/config.proto

package com.xray.app.router;

public interface BalancingRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.BalancingRule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>repeated string outbound_selector = 2;</code>
   */
  java.util.List<java.lang.String>
      getOutboundSelectorList();
  /**
   * <code>repeated string outbound_selector = 2;</code>
   */
  int getOutboundSelectorCount();
  /**
   * <code>repeated string outbound_selector = 2;</code>
   */
  java.lang.String getOutboundSelector(int index);
  /**
   * <code>repeated string outbound_selector = 2;</code>
   */
  com.google.protobuf.ByteString
      getOutboundSelectorBytes(int index);
}
