// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/config.proto

package com.xray.app.router;

public interface DomainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.Domain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Domain matching type.
   * </pre>
   *
   * <code>.xray.app.router.Domain.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   * Domain matching type.
   * </pre>
   *
   * <code>.xray.app.router.Domain.Type type = 1;</code>
   */
  com.xray.app.router.Domain.Type getType();

  /**
   * <pre>
   * Domain value.
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * Domain value.
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain.Attribute attribute = 3;</code>
   */
  java.util.List<com.xray.app.router.Domain.Attribute> 
      getAttributeList();
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain.Attribute attribute = 3;</code>
   */
  com.xray.app.router.Domain.Attribute getAttribute(int index);
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain.Attribute attribute = 3;</code>
   */
  int getAttributeCount();
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain.Attribute attribute = 3;</code>
   */
  java.util.List<? extends com.xray.app.router.Domain.AttributeOrBuilder> 
      getAttributeOrBuilderList();
  /**
   * <pre>
   * Attributes of this domain. May be used for filtering.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain.Attribute attribute = 3;</code>
   */
  com.xray.app.router.Domain.AttributeOrBuilder getAttributeOrBuilder(
      int index);
}
