// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/config.proto

package com.xray.app.router;

public interface RoutingRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.RoutingRule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Tag of outbound that this rule is pointing to.
   * </pre>
   *
   * <code>string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <pre>
   * Tag of outbound that this rule is pointing to.
   * </pre>
   *
   * <code>string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <pre>
   * Tag of routing balancer.
   * </pre>
   *
   * <code>string balancing_tag = 12;</code>
   */
  java.lang.String getBalancingTag();
  /**
   * <pre>
   * Tag of routing balancer.
   * </pre>
   *
   * <code>string balancing_tag = 12;</code>
   */
  com.google.protobuf.ByteString
      getBalancingTagBytes();

  /**
   * <pre>
   * List of domains for target domain matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  java.util.List<com.xray.app.router.Domain> 
      getDomainList();
  /**
   * <pre>
   * List of domains for target domain matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  com.xray.app.router.Domain getDomain(int index);
  /**
   * <pre>
   * List of domains for target domain matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  int getDomainCount();
  /**
   * <pre>
   * List of domains for target domain matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  java.util.List<? extends com.xray.app.router.DomainOrBuilder> 
      getDomainOrBuilderList();
  /**
   * <pre>
   * List of domains for target domain matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  com.xray.app.router.DomainOrBuilder getDomainOrBuilder(
      int index);

  /**
   * <pre>
   * List of CIDRs for target IP address matching.
   * Deprecated. Use geoip below.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR cidr = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<com.xray.app.router.CIDR> 
      getCidrList();
  /**
   * <pre>
   * List of CIDRs for target IP address matching.
   * Deprecated. Use geoip below.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR cidr = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.app.router.CIDR getCidr(int index);
  /**
   * <pre>
   * List of CIDRs for target IP address matching.
   * Deprecated. Use geoip below.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR cidr = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated int getCidrCount();
  /**
   * <pre>
   * List of CIDRs for target IP address matching.
   * Deprecated. Use geoip below.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR cidr = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<? extends com.xray.app.router.CIDROrBuilder> 
      getCidrOrBuilderList();
  /**
   * <pre>
   * List of CIDRs for target IP address matching.
   * Deprecated. Use geoip below.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR cidr = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.app.router.CIDROrBuilder getCidrOrBuilder(
      int index);

  /**
   * <pre>
   * List of GeoIPs for target IP address matching. If this entry exists, the
   * cidr above will have no effect. GeoIP fields with the same country code are
   * supposed to contain exactly same content. They will be merged during
   * runtime. For customized GeoIPs, please leave country code empty.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP geoip = 10;</code>
   */
  java.util.List<com.xray.app.router.GeoIP> 
      getGeoipList();
  /**
   * <pre>
   * List of GeoIPs for target IP address matching. If this entry exists, the
   * cidr above will have no effect. GeoIP fields with the same country code are
   * supposed to contain exactly same content. They will be merged during
   * runtime. For customized GeoIPs, please leave country code empty.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP geoip = 10;</code>
   */
  com.xray.app.router.GeoIP getGeoip(int index);
  /**
   * <pre>
   * List of GeoIPs for target IP address matching. If this entry exists, the
   * cidr above will have no effect. GeoIP fields with the same country code are
   * supposed to contain exactly same content. They will be merged during
   * runtime. For customized GeoIPs, please leave country code empty.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP geoip = 10;</code>
   */
  int getGeoipCount();
  /**
   * <pre>
   * List of GeoIPs for target IP address matching. If this entry exists, the
   * cidr above will have no effect. GeoIP fields with the same country code are
   * supposed to contain exactly same content. They will be merged during
   * runtime. For customized GeoIPs, please leave country code empty.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP geoip = 10;</code>
   */
  java.util.List<? extends com.xray.app.router.GeoIPOrBuilder> 
      getGeoipOrBuilderList();
  /**
   * <pre>
   * List of GeoIPs for target IP address matching. If this entry exists, the
   * cidr above will have no effect. GeoIP fields with the same country code are
   * supposed to contain exactly same content. They will be merged during
   * runtime. For customized GeoIPs, please leave country code empty.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP geoip = 10;</code>
   */
  com.xray.app.router.GeoIPOrBuilder getGeoipOrBuilder(
      int index);

  /**
   * <pre>
   * A range of port [from, to]. If the destination port is in this range, this
   * rule takes effect. Deprecated. Use port_list.
   * </pre>
   *
   * <code>.xray.common.net.PortRange port_range = 4 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasPortRange();
  /**
   * <pre>
   * A range of port [from, to]. If the destination port is in this range, this
   * rule takes effect. Deprecated. Use port_list.
   * </pre>
   *
   * <code>.xray.common.net.PortRange port_range = 4 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.common.net.PortRange getPortRange();
  /**
   * <pre>
   * A range of port [from, to]. If the destination port is in this range, this
   * rule takes effect. Deprecated. Use port_list.
   * </pre>
   *
   * <code>.xray.common.net.PortRange port_range = 4 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.common.net.PortRangeOrBuilder getPortRangeOrBuilder();

  /**
   * <pre>
   * List of ports.
   * </pre>
   *
   * <code>.xray.common.net.PortList port_list = 14;</code>
   */
  boolean hasPortList();
  /**
   * <pre>
   * List of ports.
   * </pre>
   *
   * <code>.xray.common.net.PortList port_list = 14;</code>
   */
  com.xray.common.net.PortList getPortList();
  /**
   * <pre>
   * List of ports.
   * </pre>
   *
   * <code>.xray.common.net.PortList port_list = 14;</code>
   */
  com.xray.common.net.PortListOrBuilder getPortListOrBuilder();

  /**
   * <pre>
   * List of networks. Deprecated. Use networks.
   * </pre>
   *
   * <code>.xray.common.net.NetworkList network_list = 5 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasNetworkList();
  /**
   * <pre>
   * List of networks. Deprecated. Use networks.
   * </pre>
   *
   * <code>.xray.common.net.NetworkList network_list = 5 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.common.net.NetworkList getNetworkList();
  /**
   * <pre>
   * List of networks. Deprecated. Use networks.
   * </pre>
   *
   * <code>.xray.common.net.NetworkList network_list = 5 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.common.net.NetworkListOrBuilder getNetworkListOrBuilder();

  /**
   * <pre>
   * List of networks for matching.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 13;</code>
   */
  java.util.List<com.xray.common.net.Network> getNetworksList();
  /**
   * <pre>
   * List of networks for matching.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 13;</code>
   */
  int getNetworksCount();
  /**
   * <pre>
   * List of networks for matching.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 13;</code>
   */
  com.xray.common.net.Network getNetworks(int index);
  /**
   * <pre>
   * List of networks for matching.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 13;</code>
   */
  java.util.List<java.lang.Integer>
  getNetworksValueList();
  /**
   * <pre>
   * List of networks for matching.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 13;</code>
   */
  int getNetworksValue(int index);

  /**
   * <pre>
   * List of CIDRs for source IP address matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR source_cidr = 6 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<com.xray.app.router.CIDR> 
      getSourceCidrList();
  /**
   * <pre>
   * List of CIDRs for source IP address matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR source_cidr = 6 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.app.router.CIDR getSourceCidr(int index);
  /**
   * <pre>
   * List of CIDRs for source IP address matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR source_cidr = 6 [deprecated = true];</code>
   */
  @java.lang.Deprecated int getSourceCidrCount();
  /**
   * <pre>
   * List of CIDRs for source IP address matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR source_cidr = 6 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<? extends com.xray.app.router.CIDROrBuilder> 
      getSourceCidrOrBuilderList();
  /**
   * <pre>
   * List of CIDRs for source IP address matching.
   * </pre>
   *
   * <code>repeated .xray.app.router.CIDR source_cidr = 6 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.app.router.CIDROrBuilder getSourceCidrOrBuilder(
      int index);

  /**
   * <pre>
   * List of GeoIPs for source IP address matching. If this entry exists, the
   * source_cidr above will have no effect.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP source_geoip = 11;</code>
   */
  java.util.List<com.xray.app.router.GeoIP> 
      getSourceGeoipList();
  /**
   * <pre>
   * List of GeoIPs for source IP address matching. If this entry exists, the
   * source_cidr above will have no effect.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP source_geoip = 11;</code>
   */
  com.xray.app.router.GeoIP getSourceGeoip(int index);
  /**
   * <pre>
   * List of GeoIPs for source IP address matching. If this entry exists, the
   * source_cidr above will have no effect.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP source_geoip = 11;</code>
   */
  int getSourceGeoipCount();
  /**
   * <pre>
   * List of GeoIPs for source IP address matching. If this entry exists, the
   * source_cidr above will have no effect.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP source_geoip = 11;</code>
   */
  java.util.List<? extends com.xray.app.router.GeoIPOrBuilder> 
      getSourceGeoipOrBuilderList();
  /**
   * <pre>
   * List of GeoIPs for source IP address matching. If this entry exists, the
   * source_cidr above will have no effect.
   * </pre>
   *
   * <code>repeated .xray.app.router.GeoIP source_geoip = 11;</code>
   */
  com.xray.app.router.GeoIPOrBuilder getSourceGeoipOrBuilder(
      int index);

  /**
   * <pre>
   * List of ports for source port matching.
   * </pre>
   *
   * <code>.xray.common.net.PortList source_port_list = 16;</code>
   */
  boolean hasSourcePortList();
  /**
   * <pre>
   * List of ports for source port matching.
   * </pre>
   *
   * <code>.xray.common.net.PortList source_port_list = 16;</code>
   */
  com.xray.common.net.PortList getSourcePortList();
  /**
   * <pre>
   * List of ports for source port matching.
   * </pre>
   *
   * <code>.xray.common.net.PortList source_port_list = 16;</code>
   */
  com.xray.common.net.PortListOrBuilder getSourcePortListOrBuilder();

  /**
   * <code>repeated string user_email = 7;</code>
   */
  java.util.List<java.lang.String>
      getUserEmailList();
  /**
   * <code>repeated string user_email = 7;</code>
   */
  int getUserEmailCount();
  /**
   * <code>repeated string user_email = 7;</code>
   */
  java.lang.String getUserEmail(int index);
  /**
   * <code>repeated string user_email = 7;</code>
   */
  com.google.protobuf.ByteString
      getUserEmailBytes(int index);

  /**
   * <code>repeated string inbound_tag = 8;</code>
   */
  java.util.List<java.lang.String>
      getInboundTagList();
  /**
   * <code>repeated string inbound_tag = 8;</code>
   */
  int getInboundTagCount();
  /**
   * <code>repeated string inbound_tag = 8;</code>
   */
  java.lang.String getInboundTag(int index);
  /**
   * <code>repeated string inbound_tag = 8;</code>
   */
  com.google.protobuf.ByteString
      getInboundTagBytes(int index);

  /**
   * <code>repeated string protocol = 9;</code>
   */
  java.util.List<java.lang.String>
      getProtocolList();
  /**
   * <code>repeated string protocol = 9;</code>
   */
  int getProtocolCount();
  /**
   * <code>repeated string protocol = 9;</code>
   */
  java.lang.String getProtocol(int index);
  /**
   * <code>repeated string protocol = 9;</code>
   */
  com.google.protobuf.ByteString
      getProtocolBytes(int index);

  /**
   * <code>string attributes = 15;</code>
   */
  java.lang.String getAttributes();
  /**
   * <code>string attributes = 15;</code>
   */
  com.google.protobuf.ByteString
      getAttributesBytes();

  public com.xray.app.router.RoutingRule.TargetTagCase getTargetTagCase();
}
