// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vmess/inbound/config.proto

package com.xray.proxy.vmess.inbound;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.vmess.inbound.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  java.util.List<com.xray.common.protocol.User> 
      getUserList();
  /**
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  com.xray.common.protocol.User getUser(int index);
  /**
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  java.util.List<? extends com.xray.common.protocol.UserOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  com.xray.common.protocol.UserOrBuilder getUserOrBuilder(
      int index);

  /**
   * <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
   */
  boolean hasDefault();
  /**
   * <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
   */
  com.xray.proxy.vmess.inbound.DefaultConfig getDefault();
  /**
   * <code>.xray.proxy.vmess.inbound.DefaultConfig default = 2;</code>
   */
  com.xray.proxy.vmess.inbound.DefaultConfigOrBuilder getDefaultOrBuilder();

  /**
   * <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
   */
  boolean hasDetour();
  /**
   * <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
   */
  com.xray.proxy.vmess.inbound.DetourConfig getDetour();
  /**
   * <code>.xray.proxy.vmess.inbound.DetourConfig detour = 3;</code>
   */
  com.xray.proxy.vmess.inbound.DetourConfigOrBuilder getDetourOrBuilder();

  /**
   * <code>bool secure_encryption_only = 4;</code>
   */
  boolean getSecureEncryptionOnly();
}
