// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vmess/inbound/config.proto

package com.xray.proxy.vmess.inbound;

public interface DefaultConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.vmess.inbound.DefaultConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 alter_id = 1;</code>
   */
  int getAlterId();

  /**
   * <code>uint32 level = 2;</code>
   */
  int getLevel();
}
