// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vmess/inbound/config.proto

package com.xray.proxy.vmess.inbound;

public interface DetourConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.vmess.inbound.DetourConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string to = 1;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 1;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();
}
