// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/dns/config.proto

package com.xray.proxy.dns;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.dns.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Server is the DNS server address. If specified, this address overrides the
   * original one.
   * </pre>
   *
   * <code>.xray.common.net.Endpoint server = 1;</code>
   */
  boolean hasServer();
  /**
   * <pre>
   * Server is the DNS server address. If specified, this address overrides the
   * original one.
   * </pre>
   *
   * <code>.xray.common.net.Endpoint server = 1;</code>
   */
  com.xray.common.net.Endpoint getServer();
  /**
   * <pre>
   * Server is the DNS server address. If specified, this address overrides the
   * original one.
   * </pre>
   *
   * <code>.xray.common.net.Endpoint server = 1;</code>
   */
  com.xray.common.net.EndpointOrBuilder getServerOrBuilder();
}
