// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/freedom/config.proto

package com.xray.proxy.freedom;

public interface DestinationOverrideOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.freedom.DestinationOverride)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  boolean hasServer();
  /**
   * <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  com.xray.common.protocol.ServerEndpoint getServer();
  /**
   * <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  com.xray.common.protocol.ServerEndpointOrBuilder getServerOrBuilder();
}
