// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package com.xray.app.proxyman;

public interface ReceiverConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.ReceiverConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * PortList specifies the ports which the Receiver should listen on.
   * </pre>
   *
   * <code>.xray.common.net.PortList port_list = 1;</code>
   * @return Whether the portList field is set.
   */
  boolean hasPortList();
  /**
   * <pre>
   * PortList specifies the ports which the Receiver should listen on.
   * </pre>
   *
   * <code>.xray.common.net.PortList port_list = 1;</code>
   * @return The portList.
   */
  com.xray.common.net.PortList getPortList();
  /**
   * <pre>
   * PortList specifies the ports which the Receiver should listen on.
   * </pre>
   *
   * <code>.xray.common.net.PortList port_list = 1;</code>
   */
  com.xray.common.net.PortListOrBuilder getPortListOrBuilder();

  /**
   * <pre>
   * Listen specifies the IP address that the Receiver should listen on.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain listen = 2;</code>
   * @return Whether the listen field is set.
   */
  boolean hasListen();
  /**
   * <pre>
   * Listen specifies the IP address that the Receiver should listen on.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain listen = 2;</code>
   * @return The listen.
   */
  com.xray.common.net.IPOrDomain getListen();
  /**
   * <pre>
   * Listen specifies the IP address that the Receiver should listen on.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain listen = 2;</code>
   */
  com.xray.common.net.IPOrDomainOrBuilder getListenOrBuilder();

  /**
   * <code>.xray.app.proxyman.AllocationStrategy allocation_strategy = 3;</code>
   * @return Whether the allocationStrategy field is set.
   */
  boolean hasAllocationStrategy();
  /**
   * <code>.xray.app.proxyman.AllocationStrategy allocation_strategy = 3;</code>
   * @return The allocationStrategy.
   */
  com.xray.app.proxyman.AllocationStrategy getAllocationStrategy();
  /**
   * <code>.xray.app.proxyman.AllocationStrategy allocation_strategy = 3;</code>
   */
  com.xray.app.proxyman.AllocationStrategyOrBuilder getAllocationStrategyOrBuilder();

  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 4;</code>
   * @return Whether the streamSettings field is set.
   */
  boolean hasStreamSettings();
  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 4;</code>
   * @return The streamSettings.
   */
  com.xray.transport.internet.StreamConfig getStreamSettings();
  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 4;</code>
   */
  com.xray.transport.internet.StreamConfigOrBuilder getStreamSettingsOrBuilder();

  /**
   * <code>bool receive_original_destination = 5;</code>
   * @return The receiveOriginalDestination.
   */
  boolean getReceiveOriginalDestination();

  /**
   * <pre>
   * Override domains for the given protocol.
   * Deprecated. Use sniffing_settings.
   * </pre>
   *
   * <code>repeated .xray.app.proxyman.KnownProtocols domain_override = 7 [deprecated = true];</code>
   * @deprecated xray.app.proxyman.ReceiverConfig.domain_override is deprecated.
   *     See app/proxyman/config.proto;l=75
   * @return A list containing the domainOverride.
   */
  @java.lang.Deprecated java.util.List<com.xray.app.proxyman.KnownProtocols> getDomainOverrideList();
  /**
   * <pre>
   * Override domains for the given protocol.
   * Deprecated. Use sniffing_settings.
   * </pre>
   *
   * <code>repeated .xray.app.proxyman.KnownProtocols domain_override = 7 [deprecated = true];</code>
   * @deprecated xray.app.proxyman.ReceiverConfig.domain_override is deprecated.
   *     See app/proxyman/config.proto;l=75
   * @return The count of domainOverride.
   */
  @java.lang.Deprecated int getDomainOverrideCount();
  /**
   * <pre>
   * Override domains for the given protocol.
   * Deprecated. Use sniffing_settings.
   * </pre>
   *
   * <code>repeated .xray.app.proxyman.KnownProtocols domain_override = 7 [deprecated = true];</code>
   * @deprecated xray.app.proxyman.ReceiverConfig.domain_override is deprecated.
   *     See app/proxyman/config.proto;l=75
   * @param index The index of the element to return.
   * @return The domainOverride at the given index.
   */
  @java.lang.Deprecated com.xray.app.proxyman.KnownProtocols getDomainOverride(int index);
  /**
   * <pre>
   * Override domains for the given protocol.
   * Deprecated. Use sniffing_settings.
   * </pre>
   *
   * <code>repeated .xray.app.proxyman.KnownProtocols domain_override = 7 [deprecated = true];</code>
   * @deprecated xray.app.proxyman.ReceiverConfig.domain_override is deprecated.
   *     See app/proxyman/config.proto;l=75
   * @return A list containing the enum numeric values on the wire for domainOverride.
   */
  @java.lang.Deprecated java.util.List<java.lang.Integer>
  getDomainOverrideValueList();
  /**
   * <pre>
   * Override domains for the given protocol.
   * Deprecated. Use sniffing_settings.
   * </pre>
   *
   * <code>repeated .xray.app.proxyman.KnownProtocols domain_override = 7 [deprecated = true];</code>
   * @deprecated xray.app.proxyman.ReceiverConfig.domain_override is deprecated.
   *     See app/proxyman/config.proto;l=75
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of domainOverride at the given index.
   */
  @java.lang.Deprecated int getDomainOverrideValue(int index);

  /**
   * <code>.xray.app.proxyman.SniffingConfig sniffing_settings = 8;</code>
   * @return Whether the sniffingSettings field is set.
   */
  boolean hasSniffingSettings();
  /**
   * <code>.xray.app.proxyman.SniffingConfig sniffing_settings = 8;</code>
   * @return The sniffingSettings.
   */
  com.xray.app.proxyman.SniffingConfig getSniffingSettings();
  /**
   * <code>.xray.app.proxyman.SniffingConfig sniffing_settings = 8;</code>
   */
  com.xray.app.proxyman.SniffingConfigOrBuilder getSniffingSettingsOrBuilder();
}
