// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package com.xray.app.proxyman;

/**
 * Protobuf type {@code xray.app.proxyman.SenderConfig}
 */
public final class SenderConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.proxyman.SenderConfig)
    SenderConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SenderConfig.newBuilder() to construct.
  private SenderConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SenderConfig() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SenderConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SenderConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SenderConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.app.proxyman.SenderConfig.class, com.xray.app.proxyman.SenderConfig.Builder.class);
  }

  public static final int VIA_FIELD_NUMBER = 1;
  private com.xray.common.net.IPOrDomain via_;
  /**
   * <pre>
   * Send traffic through the given IP. Only IP is allowed.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain via = 1;</code>
   * @return Whether the via field is set.
   */
  @java.lang.Override
  public boolean hasVia() {
    return via_ != null;
  }
  /**
   * <pre>
   * Send traffic through the given IP. Only IP is allowed.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain via = 1;</code>
   * @return The via.
   */
  @java.lang.Override
  public com.xray.common.net.IPOrDomain getVia() {
    return via_ == null ? com.xray.common.net.IPOrDomain.getDefaultInstance() : via_;
  }
  /**
   * <pre>
   * Send traffic through the given IP. Only IP is allowed.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain via = 1;</code>
   */
  @java.lang.Override
  public com.xray.common.net.IPOrDomainOrBuilder getViaOrBuilder() {
    return via_ == null ? com.xray.common.net.IPOrDomain.getDefaultInstance() : via_;
  }

  public static final int STREAM_SETTINGS_FIELD_NUMBER = 2;
  private com.xray.transport.internet.StreamConfig streamSettings_;
  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
   * @return Whether the streamSettings field is set.
   */
  @java.lang.Override
  public boolean hasStreamSettings() {
    return streamSettings_ != null;
  }
  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
   * @return The streamSettings.
   */
  @java.lang.Override
  public com.xray.transport.internet.StreamConfig getStreamSettings() {
    return streamSettings_ == null ? com.xray.transport.internet.StreamConfig.getDefaultInstance() : streamSettings_;
  }
  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
   */
  @java.lang.Override
  public com.xray.transport.internet.StreamConfigOrBuilder getStreamSettingsOrBuilder() {
    return streamSettings_ == null ? com.xray.transport.internet.StreamConfig.getDefaultInstance() : streamSettings_;
  }

  public static final int PROXY_SETTINGS_FIELD_NUMBER = 3;
  private com.xray.transport.internet.ProxyConfig proxySettings_;
  /**
   * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
   * @return Whether the proxySettings field is set.
   */
  @java.lang.Override
  public boolean hasProxySettings() {
    return proxySettings_ != null;
  }
  /**
   * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
   * @return The proxySettings.
   */
  @java.lang.Override
  public com.xray.transport.internet.ProxyConfig getProxySettings() {
    return proxySettings_ == null ? com.xray.transport.internet.ProxyConfig.getDefaultInstance() : proxySettings_;
  }
  /**
   * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
   */
  @java.lang.Override
  public com.xray.transport.internet.ProxyConfigOrBuilder getProxySettingsOrBuilder() {
    return proxySettings_ == null ? com.xray.transport.internet.ProxyConfig.getDefaultInstance() : proxySettings_;
  }

  public static final int MULTIPLEX_SETTINGS_FIELD_NUMBER = 4;
  private com.xray.app.proxyman.MultiplexingConfig multiplexSettings_;
  /**
   * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
   * @return Whether the multiplexSettings field is set.
   */
  @java.lang.Override
  public boolean hasMultiplexSettings() {
    return multiplexSettings_ != null;
  }
  /**
   * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
   * @return The multiplexSettings.
   */
  @java.lang.Override
  public com.xray.app.proxyman.MultiplexingConfig getMultiplexSettings() {
    return multiplexSettings_ == null ? com.xray.app.proxyman.MultiplexingConfig.getDefaultInstance() : multiplexSettings_;
  }
  /**
   * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
   */
  @java.lang.Override
  public com.xray.app.proxyman.MultiplexingConfigOrBuilder getMultiplexSettingsOrBuilder() {
    return multiplexSettings_ == null ? com.xray.app.proxyman.MultiplexingConfig.getDefaultInstance() : multiplexSettings_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (via_ != null) {
      output.writeMessage(1, getVia());
    }
    if (streamSettings_ != null) {
      output.writeMessage(2, getStreamSettings());
    }
    if (proxySettings_ != null) {
      output.writeMessage(3, getProxySettings());
    }
    if (multiplexSettings_ != null) {
      output.writeMessage(4, getMultiplexSettings());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (via_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVia());
    }
    if (streamSettings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStreamSettings());
    }
    if (proxySettings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getProxySettings());
    }
    if (multiplexSettings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMultiplexSettings());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.app.proxyman.SenderConfig)) {
      return super.equals(obj);
    }
    com.xray.app.proxyman.SenderConfig other = (com.xray.app.proxyman.SenderConfig) obj;

    if (hasVia() != other.hasVia()) return false;
    if (hasVia()) {
      if (!getVia()
          .equals(other.getVia())) return false;
    }
    if (hasStreamSettings() != other.hasStreamSettings()) return false;
    if (hasStreamSettings()) {
      if (!getStreamSettings()
          .equals(other.getStreamSettings())) return false;
    }
    if (hasProxySettings() != other.hasProxySettings()) return false;
    if (hasProxySettings()) {
      if (!getProxySettings()
          .equals(other.getProxySettings())) return false;
    }
    if (hasMultiplexSettings() != other.hasMultiplexSettings()) return false;
    if (hasMultiplexSettings()) {
      if (!getMultiplexSettings()
          .equals(other.getMultiplexSettings())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVia()) {
      hash = (37 * hash) + VIA_FIELD_NUMBER;
      hash = (53 * hash) + getVia().hashCode();
    }
    if (hasStreamSettings()) {
      hash = (37 * hash) + STREAM_SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getStreamSettings().hashCode();
    }
    if (hasProxySettings()) {
      hash = (37 * hash) + PROXY_SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getProxySettings().hashCode();
    }
    if (hasMultiplexSettings()) {
      hash = (37 * hash) + MULTIPLEX_SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getMultiplexSettings().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.app.proxyman.SenderConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.proxyman.SenderConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xray.app.proxyman.SenderConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.proxyman.SenderConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.app.proxyman.SenderConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.proxyman.SenderConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.proxyman.SenderConfig)
      com.xray.app.proxyman.SenderConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SenderConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SenderConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.app.proxyman.SenderConfig.class, com.xray.app.proxyman.SenderConfig.Builder.class);
    }

    // Construct using com.xray.app.proxyman.SenderConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      via_ = null;
      if (viaBuilder_ != null) {
        viaBuilder_.dispose();
        viaBuilder_ = null;
      }
      streamSettings_ = null;
      if (streamSettingsBuilder_ != null) {
        streamSettingsBuilder_.dispose();
        streamSettingsBuilder_ = null;
      }
      proxySettings_ = null;
      if (proxySettingsBuilder_ != null) {
        proxySettingsBuilder_.dispose();
        proxySettingsBuilder_ = null;
      }
      multiplexSettings_ = null;
      if (multiplexSettingsBuilder_ != null) {
        multiplexSettingsBuilder_.dispose();
        multiplexSettingsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SenderConfig_descriptor;
    }

    @java.lang.Override
    public com.xray.app.proxyman.SenderConfig getDefaultInstanceForType() {
      return com.xray.app.proxyman.SenderConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.app.proxyman.SenderConfig build() {
      com.xray.app.proxyman.SenderConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.app.proxyman.SenderConfig buildPartial() {
      com.xray.app.proxyman.SenderConfig result = new com.xray.app.proxyman.SenderConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xray.app.proxyman.SenderConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.via_ = viaBuilder_ == null
            ? via_
            : viaBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.streamSettings_ = streamSettingsBuilder_ == null
            ? streamSettings_
            : streamSettingsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.proxySettings_ = proxySettingsBuilder_ == null
            ? proxySettings_
            : proxySettingsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.multiplexSettings_ = multiplexSettingsBuilder_ == null
            ? multiplexSettings_
            : multiplexSettingsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.app.proxyman.SenderConfig) {
        return mergeFrom((com.xray.app.proxyman.SenderConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.app.proxyman.SenderConfig other) {
      if (other == com.xray.app.proxyman.SenderConfig.getDefaultInstance()) return this;
      if (other.hasVia()) {
        mergeVia(other.getVia());
      }
      if (other.hasStreamSettings()) {
        mergeStreamSettings(other.getStreamSettings());
      }
      if (other.hasProxySettings()) {
        mergeProxySettings(other.getProxySettings());
      }
      if (other.hasMultiplexSettings()) {
        mergeMultiplexSettings(other.getMultiplexSettings());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getViaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getStreamSettingsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getProxySettingsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMultiplexSettingsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.xray.common.net.IPOrDomain via_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.common.net.IPOrDomain, com.xray.common.net.IPOrDomain.Builder, com.xray.common.net.IPOrDomainOrBuilder> viaBuilder_;
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     * @return Whether the via field is set.
     */
    public boolean hasVia() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     * @return The via.
     */
    public com.xray.common.net.IPOrDomain getVia() {
      if (viaBuilder_ == null) {
        return via_ == null ? com.xray.common.net.IPOrDomain.getDefaultInstance() : via_;
      } else {
        return viaBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    public Builder setVia(com.xray.common.net.IPOrDomain value) {
      if (viaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        via_ = value;
      } else {
        viaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    public Builder setVia(
        com.xray.common.net.IPOrDomain.Builder builderForValue) {
      if (viaBuilder_ == null) {
        via_ = builderForValue.build();
      } else {
        viaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    public Builder mergeVia(com.xray.common.net.IPOrDomain value) {
      if (viaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          via_ != null &&
          via_ != com.xray.common.net.IPOrDomain.getDefaultInstance()) {
          getViaBuilder().mergeFrom(value);
        } else {
          via_ = value;
        }
      } else {
        viaBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    public Builder clearVia() {
      bitField0_ = (bitField0_ & ~0x00000001);
      via_ = null;
      if (viaBuilder_ != null) {
        viaBuilder_.dispose();
        viaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    public com.xray.common.net.IPOrDomain.Builder getViaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getViaFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    public com.xray.common.net.IPOrDomainOrBuilder getViaOrBuilder() {
      if (viaBuilder_ != null) {
        return viaBuilder_.getMessageOrBuilder();
      } else {
        return via_ == null ?
            com.xray.common.net.IPOrDomain.getDefaultInstance() : via_;
      }
    }
    /**
     * <pre>
     * Send traffic through the given IP. Only IP is allowed.
     * </pre>
     *
     * <code>.xray.common.net.IPOrDomain via = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.common.net.IPOrDomain, com.xray.common.net.IPOrDomain.Builder, com.xray.common.net.IPOrDomainOrBuilder> 
        getViaFieldBuilder() {
      if (viaBuilder_ == null) {
        viaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xray.common.net.IPOrDomain, com.xray.common.net.IPOrDomain.Builder, com.xray.common.net.IPOrDomainOrBuilder>(
                getVia(),
                getParentForChildren(),
                isClean());
        via_ = null;
      }
      return viaBuilder_;
    }

    private com.xray.transport.internet.StreamConfig streamSettings_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.transport.internet.StreamConfig, com.xray.transport.internet.StreamConfig.Builder, com.xray.transport.internet.StreamConfigOrBuilder> streamSettingsBuilder_;
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     * @return Whether the streamSettings field is set.
     */
    public boolean hasStreamSettings() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     * @return The streamSettings.
     */
    public com.xray.transport.internet.StreamConfig getStreamSettings() {
      if (streamSettingsBuilder_ == null) {
        return streamSettings_ == null ? com.xray.transport.internet.StreamConfig.getDefaultInstance() : streamSettings_;
      } else {
        return streamSettingsBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    public Builder setStreamSettings(com.xray.transport.internet.StreamConfig value) {
      if (streamSettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        streamSettings_ = value;
      } else {
        streamSettingsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    public Builder setStreamSettings(
        com.xray.transport.internet.StreamConfig.Builder builderForValue) {
      if (streamSettingsBuilder_ == null) {
        streamSettings_ = builderForValue.build();
      } else {
        streamSettingsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    public Builder mergeStreamSettings(com.xray.transport.internet.StreamConfig value) {
      if (streamSettingsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          streamSettings_ != null &&
          streamSettings_ != com.xray.transport.internet.StreamConfig.getDefaultInstance()) {
          getStreamSettingsBuilder().mergeFrom(value);
        } else {
          streamSettings_ = value;
        }
      } else {
        streamSettingsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    public Builder clearStreamSettings() {
      bitField0_ = (bitField0_ & ~0x00000002);
      streamSettings_ = null;
      if (streamSettingsBuilder_ != null) {
        streamSettingsBuilder_.dispose();
        streamSettingsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    public com.xray.transport.internet.StreamConfig.Builder getStreamSettingsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStreamSettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    public com.xray.transport.internet.StreamConfigOrBuilder getStreamSettingsOrBuilder() {
      if (streamSettingsBuilder_ != null) {
        return streamSettingsBuilder_.getMessageOrBuilder();
      } else {
        return streamSettings_ == null ?
            com.xray.transport.internet.StreamConfig.getDefaultInstance() : streamSettings_;
      }
    }
    /**
     * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.transport.internet.StreamConfig, com.xray.transport.internet.StreamConfig.Builder, com.xray.transport.internet.StreamConfigOrBuilder> 
        getStreamSettingsFieldBuilder() {
      if (streamSettingsBuilder_ == null) {
        streamSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xray.transport.internet.StreamConfig, com.xray.transport.internet.StreamConfig.Builder, com.xray.transport.internet.StreamConfigOrBuilder>(
                getStreamSettings(),
                getParentForChildren(),
                isClean());
        streamSettings_ = null;
      }
      return streamSettingsBuilder_;
    }

    private com.xray.transport.internet.ProxyConfig proxySettings_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.transport.internet.ProxyConfig, com.xray.transport.internet.ProxyConfig.Builder, com.xray.transport.internet.ProxyConfigOrBuilder> proxySettingsBuilder_;
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @return Whether the proxySettings field is set.
     */
    public boolean hasProxySettings() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @return The proxySettings.
     */
    public com.xray.transport.internet.ProxyConfig getProxySettings() {
      if (proxySettingsBuilder_ == null) {
        return proxySettings_ == null ? com.xray.transport.internet.ProxyConfig.getDefaultInstance() : proxySettings_;
      } else {
        return proxySettingsBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    public Builder setProxySettings(com.xray.transport.internet.ProxyConfig value) {
      if (proxySettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        proxySettings_ = value;
      } else {
        proxySettingsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    public Builder setProxySettings(
        com.xray.transport.internet.ProxyConfig.Builder builderForValue) {
      if (proxySettingsBuilder_ == null) {
        proxySettings_ = builderForValue.build();
      } else {
        proxySettingsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    public Builder mergeProxySettings(com.xray.transport.internet.ProxyConfig value) {
      if (proxySettingsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          proxySettings_ != null &&
          proxySettings_ != com.xray.transport.internet.ProxyConfig.getDefaultInstance()) {
          getProxySettingsBuilder().mergeFrom(value);
        } else {
          proxySettings_ = value;
        }
      } else {
        proxySettingsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    public Builder clearProxySettings() {
      bitField0_ = (bitField0_ & ~0x00000004);
      proxySettings_ = null;
      if (proxySettingsBuilder_ != null) {
        proxySettingsBuilder_.dispose();
        proxySettingsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    public com.xray.transport.internet.ProxyConfig.Builder getProxySettingsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getProxySettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    public com.xray.transport.internet.ProxyConfigOrBuilder getProxySettingsOrBuilder() {
      if (proxySettingsBuilder_ != null) {
        return proxySettingsBuilder_.getMessageOrBuilder();
      } else {
        return proxySettings_ == null ?
            com.xray.transport.internet.ProxyConfig.getDefaultInstance() : proxySettings_;
      }
    }
    /**
     * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.transport.internet.ProxyConfig, com.xray.transport.internet.ProxyConfig.Builder, com.xray.transport.internet.ProxyConfigOrBuilder> 
        getProxySettingsFieldBuilder() {
      if (proxySettingsBuilder_ == null) {
        proxySettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xray.transport.internet.ProxyConfig, com.xray.transport.internet.ProxyConfig.Builder, com.xray.transport.internet.ProxyConfigOrBuilder>(
                getProxySettings(),
                getParentForChildren(),
                isClean());
        proxySettings_ = null;
      }
      return proxySettingsBuilder_;
    }

    private com.xray.app.proxyman.MultiplexingConfig multiplexSettings_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.proxyman.MultiplexingConfig, com.xray.app.proxyman.MultiplexingConfig.Builder, com.xray.app.proxyman.MultiplexingConfigOrBuilder> multiplexSettingsBuilder_;
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @return Whether the multiplexSettings field is set.
     */
    public boolean hasMultiplexSettings() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @return The multiplexSettings.
     */
    public com.xray.app.proxyman.MultiplexingConfig getMultiplexSettings() {
      if (multiplexSettingsBuilder_ == null) {
        return multiplexSettings_ == null ? com.xray.app.proxyman.MultiplexingConfig.getDefaultInstance() : multiplexSettings_;
      } else {
        return multiplexSettingsBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    public Builder setMultiplexSettings(com.xray.app.proxyman.MultiplexingConfig value) {
      if (multiplexSettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        multiplexSettings_ = value;
      } else {
        multiplexSettingsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    public Builder setMultiplexSettings(
        com.xray.app.proxyman.MultiplexingConfig.Builder builderForValue) {
      if (multiplexSettingsBuilder_ == null) {
        multiplexSettings_ = builderForValue.build();
      } else {
        multiplexSettingsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    public Builder mergeMultiplexSettings(com.xray.app.proxyman.MultiplexingConfig value) {
      if (multiplexSettingsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          multiplexSettings_ != null &&
          multiplexSettings_ != com.xray.app.proxyman.MultiplexingConfig.getDefaultInstance()) {
          getMultiplexSettingsBuilder().mergeFrom(value);
        } else {
          multiplexSettings_ = value;
        }
      } else {
        multiplexSettingsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    public Builder clearMultiplexSettings() {
      bitField0_ = (bitField0_ & ~0x00000008);
      multiplexSettings_ = null;
      if (multiplexSettingsBuilder_ != null) {
        multiplexSettingsBuilder_.dispose();
        multiplexSettingsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    public com.xray.app.proxyman.MultiplexingConfig.Builder getMultiplexSettingsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getMultiplexSettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    public com.xray.app.proxyman.MultiplexingConfigOrBuilder getMultiplexSettingsOrBuilder() {
      if (multiplexSettingsBuilder_ != null) {
        return multiplexSettingsBuilder_.getMessageOrBuilder();
      } else {
        return multiplexSettings_ == null ?
            com.xray.app.proxyman.MultiplexingConfig.getDefaultInstance() : multiplexSettings_;
      }
    }
    /**
     * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xray.app.proxyman.MultiplexingConfig, com.xray.app.proxyman.MultiplexingConfig.Builder, com.xray.app.proxyman.MultiplexingConfigOrBuilder> 
        getMultiplexSettingsFieldBuilder() {
      if (multiplexSettingsBuilder_ == null) {
        multiplexSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xray.app.proxyman.MultiplexingConfig, com.xray.app.proxyman.MultiplexingConfig.Builder, com.xray.app.proxyman.MultiplexingConfigOrBuilder>(
                getMultiplexSettings(),
                getParentForChildren(),
                isClean());
        multiplexSettings_ = null;
      }
      return multiplexSettingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.proxyman.SenderConfig)
  }

  // @@protoc_insertion_point(class_scope:xray.app.proxyman.SenderConfig)
  private static final com.xray.app.proxyman.SenderConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.app.proxyman.SenderConfig();
  }

  public static com.xray.app.proxyman.SenderConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SenderConfig>
      PARSER = new com.google.protobuf.AbstractParser<SenderConfig>() {
    @java.lang.Override
    public SenderConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SenderConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SenderConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.app.proxyman.SenderConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

