// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package com.xray.app.proxyman;

public interface SenderConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.SenderConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Send traffic through the given IP. Only IP is allowed.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain via = 1;</code>
   */
  boolean hasVia();
  /**
   * <pre>
   * Send traffic through the given IP. Only IP is allowed.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain via = 1;</code>
   */
  com.xray.common.net.IPOrDomain getVia();
  /**
   * <pre>
   * Send traffic through the given IP. Only IP is allowed.
   * </pre>
   *
   * <code>.xray.common.net.IPOrDomain via = 1;</code>
   */
  com.xray.common.net.IPOrDomainOrBuilder getViaOrBuilder();

  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
   */
  boolean hasStreamSettings();
  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
   */
  com.xray.transport.internet.StreamConfig getStreamSettings();
  /**
   * <code>.xray.transport.internet.StreamConfig stream_settings = 2;</code>
   */
  com.xray.transport.internet.StreamConfigOrBuilder getStreamSettingsOrBuilder();

  /**
   * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
   */
  boolean hasProxySettings();
  /**
   * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
   */
  com.xray.transport.internet.ProxyConfig getProxySettings();
  /**
   * <code>.xray.transport.internet.ProxyConfig proxy_settings = 3;</code>
   */
  com.xray.transport.internet.ProxyConfigOrBuilder getProxySettingsOrBuilder();

  /**
   * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
   */
  boolean hasMultiplexSettings();
  /**
   * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
   */
  com.xray.app.proxyman.MultiplexingConfig getMultiplexSettings();
  /**
   * <code>.xray.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
   */
  com.xray.app.proxyman.MultiplexingConfigOrBuilder getMultiplexSettingsOrBuilder();
}
