// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package com.xray.app.proxyman;

public interface SniffingConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.SniffingConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether or not to enable content sniffing on an inbound connection.
   * </pre>
   *
   * <code>bool enabled = 1;</code>
   */
  boolean getEnabled();

  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  java.util.List<java.lang.String>
      getDestinationOverrideList();
  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  int getDestinationOverrideCount();
  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  java.lang.String getDestinationOverride(int index);
  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestinationOverrideBytes(int index);

  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  java.util.List<java.lang.String>
      getDomainsExcludedList();
  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  int getDomainsExcludedCount();
  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  java.lang.String getDomainsExcluded(int index);
  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  com.google.protobuf.ByteString
      getDomainsExcludedBytes(int index);
}
