// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package com.xray.app.proxyman;

/**
 * Protobuf type {@code xray.app.proxyman.SniffingConfig}
 */
public  final class SniffingConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.proxyman.SniffingConfig)
    SniffingConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SniffingConfig.newBuilder() to construct.
  private SniffingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SniffingConfig() {
    destinationOverride_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    domainsExcluded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SniffingConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            enabled_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              destinationOverride_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            destinationOverride_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              domainsExcluded_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            domainsExcluded_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        destinationOverride_ = destinationOverride_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        domainsExcluded_ = domainsExcluded_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SniffingConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SniffingConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.app.proxyman.SniffingConfig.class, com.xray.app.proxyman.SniffingConfig.Builder.class);
  }

  private int bitField0_;
  public static final int ENABLED_FIELD_NUMBER = 1;
  private boolean enabled_;
  /**
   * <pre>
   * Whether or not to enable content sniffing on an inbound connection.
   * </pre>
   *
   * <code>bool enabled = 1;</code>
   */
  public boolean getEnabled() {
    return enabled_;
  }

  public static final int DESTINATION_OVERRIDE_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList destinationOverride_;
  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDestinationOverrideList() {
    return destinationOverride_;
  }
  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  public int getDestinationOverrideCount() {
    return destinationOverride_.size();
  }
  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  public java.lang.String getDestinationOverride(int index) {
    return destinationOverride_.get(index);
  }
  /**
   * <pre>
   * Override target destination if sniff'ed protocol is in the given list.
   * Supported values are "http", "tls".
   * </pre>
   *
   * <code>repeated string destination_override = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationOverrideBytes(int index) {
    return destinationOverride_.getByteString(index);
  }

  public static final int DOMAINS_EXCLUDED_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList domainsExcluded_;
  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDomainsExcludedList() {
    return domainsExcluded_;
  }
  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  public int getDomainsExcludedCount() {
    return domainsExcluded_.size();
  }
  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  public java.lang.String getDomainsExcluded(int index) {
    return domainsExcluded_.get(index);
  }
  /**
   * <code>repeated string domains_excluded = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDomainsExcludedBytes(int index) {
    return domainsExcluded_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (enabled_ != false) {
      output.writeBool(1, enabled_);
    }
    for (int i = 0; i < destinationOverride_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destinationOverride_.getRaw(i));
    }
    for (int i = 0; i < domainsExcluded_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, domainsExcluded_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, enabled_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < destinationOverride_.size(); i++) {
        dataSize += computeStringSizeNoTag(destinationOverride_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDestinationOverrideList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < domainsExcluded_.size(); i++) {
        dataSize += computeStringSizeNoTag(domainsExcluded_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDomainsExcludedList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.app.proxyman.SniffingConfig)) {
      return super.equals(obj);
    }
    com.xray.app.proxyman.SniffingConfig other = (com.xray.app.proxyman.SniffingConfig) obj;

    if (getEnabled()
        != other.getEnabled()) return false;
    if (!getDestinationOverrideList()
        .equals(other.getDestinationOverrideList())) return false;
    if (!getDomainsExcludedList()
        .equals(other.getDomainsExcludedList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnabled());
    if (getDestinationOverrideCount() > 0) {
      hash = (37 * hash) + DESTINATION_OVERRIDE_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationOverrideList().hashCode();
    }
    if (getDomainsExcludedCount() > 0) {
      hash = (37 * hash) + DOMAINS_EXCLUDED_FIELD_NUMBER;
      hash = (53 * hash) + getDomainsExcludedList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.proxyman.SniffingConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xray.app.proxyman.SniffingConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.app.proxyman.SniffingConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.app.proxyman.SniffingConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.proxyman.SniffingConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.proxyman.SniffingConfig)
      com.xray.app.proxyman.SniffingConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SniffingConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SniffingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.app.proxyman.SniffingConfig.class, com.xray.app.proxyman.SniffingConfig.Builder.class);
    }

    // Construct using com.xray.app.proxyman.SniffingConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      enabled_ = false;

      destinationOverride_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      domainsExcluded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.app.proxyman.Config.internal_static_xray_app_proxyman_SniffingConfig_descriptor;
    }

    @java.lang.Override
    public com.xray.app.proxyman.SniffingConfig getDefaultInstanceForType() {
      return com.xray.app.proxyman.SniffingConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.app.proxyman.SniffingConfig build() {
      com.xray.app.proxyman.SniffingConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.app.proxyman.SniffingConfig buildPartial() {
      com.xray.app.proxyman.SniffingConfig result = new com.xray.app.proxyman.SniffingConfig(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.enabled_ = enabled_;
      if (((bitField0_ & 0x00000002) != 0)) {
        destinationOverride_ = destinationOverride_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.destinationOverride_ = destinationOverride_;
      if (((bitField0_ & 0x00000004) != 0)) {
        domainsExcluded_ = domainsExcluded_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.domainsExcluded_ = domainsExcluded_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.app.proxyman.SniffingConfig) {
        return mergeFrom((com.xray.app.proxyman.SniffingConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.app.proxyman.SniffingConfig other) {
      if (other == com.xray.app.proxyman.SniffingConfig.getDefaultInstance()) return this;
      if (other.getEnabled() != false) {
        setEnabled(other.getEnabled());
      }
      if (!other.destinationOverride_.isEmpty()) {
        if (destinationOverride_.isEmpty()) {
          destinationOverride_ = other.destinationOverride_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDestinationOverrideIsMutable();
          destinationOverride_.addAll(other.destinationOverride_);
        }
        onChanged();
      }
      if (!other.domainsExcluded_.isEmpty()) {
        if (domainsExcluded_.isEmpty()) {
          domainsExcluded_ = other.domainsExcluded_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDomainsExcludedIsMutable();
          domainsExcluded_.addAll(other.domainsExcluded_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xray.app.proxyman.SniffingConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xray.app.proxyman.SniffingConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean enabled_ ;
    /**
     * <pre>
     * Whether or not to enable content sniffing on an inbound connection.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     */
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <pre>
     * Whether or not to enable content sniffing on an inbound connection.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     */
    public Builder setEnabled(boolean value) {
      
      enabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether or not to enable content sniffing on an inbound connection.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     */
    public Builder clearEnabled() {
      
      enabled_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList destinationOverride_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDestinationOverrideIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        destinationOverride_ = new com.google.protobuf.LazyStringArrayList(destinationOverride_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDestinationOverrideList() {
      return destinationOverride_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public int getDestinationOverrideCount() {
      return destinationOverride_.size();
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public java.lang.String getDestinationOverride(int index) {
      return destinationOverride_.get(index);
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationOverrideBytes(int index) {
      return destinationOverride_.getByteString(index);
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public Builder setDestinationOverride(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDestinationOverrideIsMutable();
      destinationOverride_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public Builder addDestinationOverride(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDestinationOverrideIsMutable();
      destinationOverride_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public Builder addAllDestinationOverride(
        java.lang.Iterable<java.lang.String> values) {
      ensureDestinationOverrideIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, destinationOverride_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public Builder clearDestinationOverride() {
      destinationOverride_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Override target destination if sniff'ed protocol is in the given list.
     * Supported values are "http", "tls".
     * </pre>
     *
     * <code>repeated string destination_override = 2;</code>
     */
    public Builder addDestinationOverrideBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDestinationOverrideIsMutable();
      destinationOverride_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList domainsExcluded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDomainsExcludedIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        domainsExcluded_ = new com.google.protobuf.LazyStringArrayList(domainsExcluded_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDomainsExcludedList() {
      return domainsExcluded_.getUnmodifiableView();
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public int getDomainsExcludedCount() {
      return domainsExcluded_.size();
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public java.lang.String getDomainsExcluded(int index) {
      return domainsExcluded_.get(index);
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDomainsExcludedBytes(int index) {
      return domainsExcluded_.getByteString(index);
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public Builder setDomainsExcluded(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDomainsExcludedIsMutable();
      domainsExcluded_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public Builder addDomainsExcluded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDomainsExcludedIsMutable();
      domainsExcluded_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public Builder addAllDomainsExcluded(
        java.lang.Iterable<java.lang.String> values) {
      ensureDomainsExcludedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, domainsExcluded_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public Builder clearDomainsExcluded() {
      domainsExcluded_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domains_excluded = 3;</code>
     */
    public Builder addDomainsExcludedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDomainsExcludedIsMutable();
      domainsExcluded_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.proxyman.SniffingConfig)
  }

  // @@protoc_insertion_point(class_scope:xray.app.proxyman.SniffingConfig)
  private static final com.xray.app.proxyman.SniffingConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.app.proxyman.SniffingConfig();
  }

  public static com.xray.app.proxyman.SniffingConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SniffingConfig>
      PARSER = new com.google.protobuf.AbstractParser<SniffingConfig>() {
    @java.lang.Override
    public SniffingConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SniffingConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SniffingConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SniffingConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.app.proxyman.SniffingConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

