// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vmess/account.proto

package com.xray.proxy.vmess;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.vmess.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the account, in the form of a UUID, e.g.,
   * "66ad4540-b58c-4ad2-9926-ea63445a9b57".
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * ID of the account, in the form of a UUID, e.g.,
   * "66ad4540-b58c-4ad2-9926-ea63445a9b57".
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Number of alternative IDs. Client and server must share the same number.
   * </pre>
   *
   * <code>uint32 alter_id = 2;</code>
   */
  int getAlterId();

  /**
   * <pre>
   * Security settings. Only applies to client side.
   * </pre>
   *
   * <code>.xray.common.protocol.SecurityConfig security_settings = 3;</code>
   */
  boolean hasSecuritySettings();
  /**
   * <pre>
   * Security settings. Only applies to client side.
   * </pre>
   *
   * <code>.xray.common.protocol.SecurityConfig security_settings = 3;</code>
   */
  com.xray.common.protocol.SecurityConfig getSecuritySettings();
  /**
   * <pre>
   * Security settings. Only applies to client side.
   * </pre>
   *
   * <code>.xray.common.protocol.SecurityConfig security_settings = 3;</code>
   */
  com.xray.common.protocol.SecurityConfigOrBuilder getSecuritySettingsOrBuilder();

  /**
   * <pre>
   * Define tests enabled for this account
   * </pre>
   *
   * <code>string tests_enabled = 4;</code>
   */
  java.lang.String getTestsEnabled();
  /**
   * <pre>
   * Define tests enabled for this account
   * </pre>
   *
   * <code>string tests_enabled = 4;</code>
   */
  com.google.protobuf.ByteString
      getTestsEnabledBytes();
}
