// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

package com.xray.app.router.command;

public interface RoutingContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.command.RoutingContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string InboundTag = 1;</code>
   */
  java.lang.String getInboundTag();
  /**
   * <code>string InboundTag = 1;</code>
   */
  com.google.protobuf.ByteString
      getInboundTagBytes();

  /**
   * <code>.xray.common.net.Network Network = 2;</code>
   */
  int getNetworkValue();
  /**
   * <code>.xray.common.net.Network Network = 2;</code>
   */
  com.xray.common.net.Network getNetwork();

  /**
   * <code>repeated bytes SourceIPs = 3;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getSourceIPsList();
  /**
   * <code>repeated bytes SourceIPs = 3;</code>
   */
  int getSourceIPsCount();
  /**
   * <code>repeated bytes SourceIPs = 3;</code>
   */
  com.google.protobuf.ByteString getSourceIPs(int index);

  /**
   * <code>repeated bytes TargetIPs = 4;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getTargetIPsList();
  /**
   * <code>repeated bytes TargetIPs = 4;</code>
   */
  int getTargetIPsCount();
  /**
   * <code>repeated bytes TargetIPs = 4;</code>
   */
  com.google.protobuf.ByteString getTargetIPs(int index);

  /**
   * <code>uint32 SourcePort = 5;</code>
   */
  int getSourcePort();

  /**
   * <code>uint32 TargetPort = 6;</code>
   */
  int getTargetPort();

  /**
   * <code>string TargetDomain = 7;</code>
   */
  java.lang.String getTargetDomain();
  /**
   * <code>string TargetDomain = 7;</code>
   */
  com.google.protobuf.ByteString
      getTargetDomainBytes();

  /**
   * <code>string Protocol = 8;</code>
   */
  java.lang.String getProtocol();
  /**
   * <code>string Protocol = 8;</code>
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <code>string User = 9;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string User = 9;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */

  java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */

  java.lang.String getAttributesOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   */
  java.util.List<java.lang.String>
      getOutboundGroupTagsList();
  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   */
  int getOutboundGroupTagsCount();
  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   */
  java.lang.String getOutboundGroupTags(int index);
  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   */
  com.google.protobuf.ByteString
      getOutboundGroupTagsBytes(int index);

  /**
   * <code>string OutboundTag = 12;</code>
   */
  java.lang.String getOutboundTag();
  /**
   * <code>string OutboundTag = 12;</code>
   */
  com.google.protobuf.ByteString
      getOutboundTagBytes();
}
