// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

package com.xray.app.router.command;

public interface SubscribeRoutingStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.command.SubscribeRoutingStatsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string FieldSelectors = 1;</code>
   */
  java.util.List<java.lang.String>
      getFieldSelectorsList();
  /**
   * <code>repeated string FieldSelectors = 1;</code>
   */
  int getFieldSelectorsCount();
  /**
   * <code>repeated string FieldSelectors = 1;</code>
   */
  java.lang.String getFieldSelectors(int index);
  /**
   * <code>repeated string FieldSelectors = 1;</code>
   */
  com.google.protobuf.ByteString
      getFieldSelectorsBytes(int index);
}
