// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

package com.xray.app.router.command;

public interface TestRouteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.command.TestRouteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.app.router.command.RoutingContext RoutingContext = 1;</code>
   */
  boolean hasRoutingContext();
  /**
   * <code>.xray.app.router.command.RoutingContext RoutingContext = 1;</code>
   */
  com.xray.app.router.command.RoutingContext getRoutingContext();
  /**
   * <code>.xray.app.router.command.RoutingContext RoutingContext = 1;</code>
   */
  com.xray.app.router.command.RoutingContextOrBuilder getRoutingContextOrBuilder();

  /**
   * <code>repeated string FieldSelectors = 2;</code>
   */
  java.util.List<java.lang.String>
      getFieldSelectorsList();
  /**
   * <code>repeated string FieldSelectors = 2;</code>
   */
  int getFieldSelectorsCount();
  /**
   * <code>repeated string FieldSelectors = 2;</code>
   */
  java.lang.String getFieldSelectors(int index);
  /**
   * <code>repeated string FieldSelectors = 2;</code>
   */
  com.google.protobuf.ByteString
      getFieldSelectorsBytes(int index);

  /**
   * <code>bool PublishResult = 3;</code>
   */
  boolean getPublishResult();
}
