// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/trojan/config.proto

package com.xray.proxy.trojan;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.trojan.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string flow = 2;</code>
   */
  java.lang.String getFlow();
  /**
   * <code>string flow = 2;</code>
   */
  com.google.protobuf.ByteString
      getFlowBytes();
}
