// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/trojan/config.proto

package com.xray.proxy.trojan;

public interface FallbackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.trojan.Fallback)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string alpn = 2;</code>
   */
  java.lang.String getAlpn();
  /**
   * <code>string alpn = 2;</code>
   */
  com.google.protobuf.ByteString
      getAlpnBytes();

  /**
   * <code>string path = 3;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 3;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string dest = 5;</code>
   */
  java.lang.String getDest();
  /**
   * <code>string dest = 5;</code>
   */
  com.google.protobuf.ByteString
      getDestBytes();

  /**
   * <code>uint64 xver = 6;</code>
   */
  long getXver();
}
