// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/kcp/config.proto

package com.xray.transport.internet.kcp;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.kcp.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.transport.internet.kcp.MTU mtu = 1;</code>
   */
  boolean hasMtu();
  /**
   * <code>.xray.transport.internet.kcp.MTU mtu = 1;</code>
   */
  com.xray.transport.internet.kcp.MTU getMtu();
  /**
   * <code>.xray.transport.internet.kcp.MTU mtu = 1;</code>
   */
  com.xray.transport.internet.kcp.MTUOrBuilder getMtuOrBuilder();

  /**
   * <code>.xray.transport.internet.kcp.TTI tti = 2;</code>
   */
  boolean hasTti();
  /**
   * <code>.xray.transport.internet.kcp.TTI tti = 2;</code>
   */
  com.xray.transport.internet.kcp.TTI getTti();
  /**
   * <code>.xray.transport.internet.kcp.TTI tti = 2;</code>
   */
  com.xray.transport.internet.kcp.TTIOrBuilder getTtiOrBuilder();

  /**
   * <code>.xray.transport.internet.kcp.UplinkCapacity uplink_capacity = 3;</code>
   */
  boolean hasUplinkCapacity();
  /**
   * <code>.xray.transport.internet.kcp.UplinkCapacity uplink_capacity = 3;</code>
   */
  com.xray.transport.internet.kcp.UplinkCapacity getUplinkCapacity();
  /**
   * <code>.xray.transport.internet.kcp.UplinkCapacity uplink_capacity = 3;</code>
   */
  com.xray.transport.internet.kcp.UplinkCapacityOrBuilder getUplinkCapacityOrBuilder();

  /**
   * <code>.xray.transport.internet.kcp.DownlinkCapacity downlink_capacity = 4;</code>
   */
  boolean hasDownlinkCapacity();
  /**
   * <code>.xray.transport.internet.kcp.DownlinkCapacity downlink_capacity = 4;</code>
   */
  com.xray.transport.internet.kcp.DownlinkCapacity getDownlinkCapacity();
  /**
   * <code>.xray.transport.internet.kcp.DownlinkCapacity downlink_capacity = 4;</code>
   */
  com.xray.transport.internet.kcp.DownlinkCapacityOrBuilder getDownlinkCapacityOrBuilder();

  /**
   * <code>bool congestion = 5;</code>
   */
  boolean getCongestion();

  /**
   * <code>.xray.transport.internet.kcp.WriteBuffer write_buffer = 6;</code>
   */
  boolean hasWriteBuffer();
  /**
   * <code>.xray.transport.internet.kcp.WriteBuffer write_buffer = 6;</code>
   */
  com.xray.transport.internet.kcp.WriteBuffer getWriteBuffer();
  /**
   * <code>.xray.transport.internet.kcp.WriteBuffer write_buffer = 6;</code>
   */
  com.xray.transport.internet.kcp.WriteBufferOrBuilder getWriteBufferOrBuilder();

  /**
   * <code>.xray.transport.internet.kcp.ReadBuffer read_buffer = 7;</code>
   */
  boolean hasReadBuffer();
  /**
   * <code>.xray.transport.internet.kcp.ReadBuffer read_buffer = 7;</code>
   */
  com.xray.transport.internet.kcp.ReadBuffer getReadBuffer();
  /**
   * <code>.xray.transport.internet.kcp.ReadBuffer read_buffer = 7;</code>
   */
  com.xray.transport.internet.kcp.ReadBufferOrBuilder getReadBufferOrBuilder();

  /**
   * <code>.xray.common.serial.TypedMessage header_config = 8;</code>
   */
  boolean hasHeaderConfig();
  /**
   * <code>.xray.common.serial.TypedMessage header_config = 8;</code>
   */
  com.xray.common.serial.TypedMessage getHeaderConfig();
  /**
   * <code>.xray.common.serial.TypedMessage header_config = 8;</code>
   */
  com.xray.common.serial.TypedMessageOrBuilder getHeaderConfigOrBuilder();

  /**
   * <code>.xray.transport.internet.kcp.EncryptionSeed seed = 10;</code>
   */
  boolean hasSeed();
  /**
   * <code>.xray.transport.internet.kcp.EncryptionSeed seed = 10;</code>
   */
  com.xray.transport.internet.kcp.EncryptionSeed getSeed();
  /**
   * <code>.xray.transport.internet.kcp.EncryptionSeed seed = 10;</code>
   */
  com.xray.transport.internet.kcp.EncryptionSeedOrBuilder getSeedOrBuilder();
}
