// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/kcp/config.proto

package com.xray.transport.internet.kcp;

public interface EncryptionSeedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.kcp.EncryptionSeed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string seed = 1;</code>
   */
  java.lang.String getSeed();
  /**
   * <code>string seed = 1;</code>
   */
  com.google.protobuf.ByteString
      getSeedBytes();
}
