// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vless/account.proto

package com.xray.proxy.vless;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.vless.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Flow settings. May be "xtls-rprx-direct".
   * </pre>
   *
   * <code>string flow = 2;</code>
   */
  java.lang.String getFlow();
  /**
   * <pre>
   * Flow settings. May be "xtls-rprx-direct".
   * </pre>
   *
   * <code>string flow = 2;</code>
   */
  com.google.protobuf.ByteString
      getFlowBytes();

  /**
   * <pre>
   * Encryption settings. Only applies to client side, and only accepts "none" for now.
   * </pre>
   *
   * <code>string encryption = 3;</code>
   */
  java.lang.String getEncryption();
  /**
   * <pre>
   * Encryption settings. Only applies to client side, and only accepts "none" for now.
   * </pre>
   *
   * <code>string encryption = 3;</code>
   */
  com.google.protobuf.ByteString
      getEncryptionBytes();
}
