// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/net/destination.proto

package com.xray.common.net;

public interface EndpointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.common.net.Endpoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.common.net.Network network = 1;</code>
   */
  int getNetworkValue();
  /**
   * <code>.xray.common.net.Network network = 1;</code>
   */
  com.xray.common.net.Network getNetwork();

  /**
   * <code>.xray.common.net.IPOrDomain address = 2;</code>
   */
  boolean hasAddress();
  /**
   * <code>.xray.common.net.IPOrDomain address = 2;</code>
   */
  com.xray.common.net.IPOrDomain getAddress();
  /**
   * <code>.xray.common.net.IPOrDomain address = 2;</code>
   */
  com.xray.common.net.IPOrDomainOrBuilder getAddressOrBuilder();

  /**
   * <code>uint32 port = 3;</code>
   */
  int getPort();
}
