// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/net/network.proto

package com.xray.common.net;

public interface NetworkListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.common.net.NetworkList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.common.net.Network network = 1;</code>
   */
  java.util.List<com.xray.common.net.Network> getNetworkList();
  /**
   * <code>repeated .xray.common.net.Network network = 1;</code>
   */
  int getNetworkCount();
  /**
   * <code>repeated .xray.common.net.Network network = 1;</code>
   */
  com.xray.common.net.Network getNetwork(int index);
  /**
   * <code>repeated .xray.common.net.Network network = 1;</code>
   */
  java.util.List<java.lang.Integer>
  getNetworkValueList();
  /**
   * <code>repeated .xray.common.net.Network network = 1;</code>
   */
  int getNetworkValue(int index);
}
