// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/quic/config.proto

package com.xray.transport.internet.quic;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.quic.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.xray.common.protocol.SecurityConfig security = 2;</code>
   */
  boolean hasSecurity();
  /**
   * <code>.xray.common.protocol.SecurityConfig security = 2;</code>
   */
  com.xray.common.protocol.SecurityConfig getSecurity();
  /**
   * <code>.xray.common.protocol.SecurityConfig security = 2;</code>
   */
  com.xray.common.protocol.SecurityConfigOrBuilder getSecurityOrBuilder();

  /**
   * <code>.xray.common.serial.TypedMessage header = 3;</code>
   */
  boolean hasHeader();
  /**
   * <code>.xray.common.serial.TypedMessage header = 3;</code>
   */
  com.xray.common.serial.TypedMessage getHeader();
  /**
   * <code>.xray.common.serial.TypedMessage header = 3;</code>
   */
  com.xray.common.serial.TypedMessageOrBuilder getHeaderOrBuilder();
}
