// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/dokodemo/config.proto

package com.xray.proxy.dokodemo;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.dokodemo.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.common.net.IPOrDomain address = 1;</code>
   */
  boolean hasAddress();
  /**
   * <code>.xray.common.net.IPOrDomain address = 1;</code>
   */
  com.xray.common.net.IPOrDomain getAddress();
  /**
   * <code>.xray.common.net.IPOrDomain address = 1;</code>
   */
  com.xray.common.net.IPOrDomainOrBuilder getAddressOrBuilder();

  /**
   * <code>uint32 port = 2;</code>
   */
  int getPort();

  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * Deprecated. Use networks.
   * </pre>
   *
   * <code>.xray.common.net.NetworkList network_list = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasNetworkList();
  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * Deprecated. Use networks.
   * </pre>
   *
   * <code>.xray.common.net.NetworkList network_list = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.common.net.NetworkList getNetworkList();
  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * Deprecated. Use networks.
   * </pre>
   *
   * <code>.xray.common.net.NetworkList network_list = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.common.net.NetworkListOrBuilder getNetworkListOrBuilder();

  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 7;</code>
   */
  java.util.List<com.xray.common.net.Network> getNetworksList();
  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 7;</code>
   */
  int getNetworksCount();
  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 7;</code>
   */
  com.xray.common.net.Network getNetworks(int index);
  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 7;</code>
   */
  java.util.List<java.lang.Integer>
  getNetworksValueList();
  /**
   * <pre>
   * List of networks that the Dokodemo accepts.
   * </pre>
   *
   * <code>repeated .xray.common.net.Network networks = 7;</code>
   */
  int getNetworksValue(int index);

  /**
   * <code>uint32 timeout = 4 [deprecated = true];</code>
   */
  @java.lang.Deprecated int getTimeout();

  /**
   * <code>bool follow_redirect = 5;</code>
   */
  boolean getFollowRedirect();

  /**
   * <code>uint32 user_level = 6;</code>
   */
  int getUserLevel();
}
