// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/log/config.proto

package com.xray.app.log;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.log.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.app.log.LogType error_log_type = 1;</code>
   */
  int getErrorLogTypeValue();
  /**
   * <code>.xray.app.log.LogType error_log_type = 1;</code>
   */
  com.xray.app.log.LogType getErrorLogType();

  /**
   * <code>.xray.common.log.Severity error_log_level = 2;</code>
   */
  int getErrorLogLevelValue();
  /**
   * <code>.xray.common.log.Severity error_log_level = 2;</code>
   */
  com.xray.common.log.Severity getErrorLogLevel();

  /**
   * <code>string error_log_path = 3;</code>
   */
  java.lang.String getErrorLogPath();
  /**
   * <code>string error_log_path = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorLogPathBytes();

  /**
   * <code>.xray.app.log.LogType access_log_type = 4;</code>
   */
  int getAccessLogTypeValue();
  /**
   * <code>.xray.app.log.LogType access_log_type = 4;</code>
   */
  com.xray.app.log.LogType getAccessLogType();

  /**
   * <code>string access_log_path = 5;</code>
   */
  java.lang.String getAccessLogPath();
  /**
   * <code>string access_log_path = 5;</code>
   */
  com.google.protobuf.ByteString
      getAccessLogPathBytes();
}
