// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/command/command.proto

package com.xray.app.proxyman.command;

public interface AddInboundRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.command.AddInboundRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  boolean hasInbound();
  /**
   * <code>.xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  com.xray.core.InboundHandlerConfig getInbound();
  /**
   * <code>.xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  com.xray.core.InboundHandlerConfigOrBuilder getInboundOrBuilder();
}
