// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/command/command.proto

package com.xray.app.proxyman.command;

public interface AddUserOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.command.AddUserOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.common.protocol.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.xray.common.protocol.User user = 1;</code>
   */
  com.xray.common.protocol.User getUser();
  /**
   * <code>.xray.common.protocol.User user = 1;</code>
   */
  com.xray.common.protocol.UserOrBuilder getUserOrBuilder();
}
