// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

package com.xray.app.stats.command;

public interface GetStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.GetStatsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the stat counter.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the stat counter.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Whether or not to reset the counter to fetching its value.
   * </pre>
   *
   * <code>bool reset = 2;</code>
   */
  boolean getReset();
}
