// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

package com.xray.app.stats.command;

public interface SysStatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.stats.command.SysStatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 NumGoroutine = 1;</code>
   */
  int getNumGoroutine();

  /**
   * <code>uint32 NumGC = 2;</code>
   */
  int getNumGC();

  /**
   * <code>uint64 Alloc = 3;</code>
   */
  long getAlloc();

  /**
   * <code>uint64 TotalAlloc = 4;</code>
   */
  long getTotalAlloc();

  /**
   * <code>uint64 Sys = 5;</code>
   */
  long getSys();

  /**
   * <code>uint64 Mallocs = 6;</code>
   */
  long getMallocs();

  /**
   * <code>uint64 Frees = 7;</code>
   */
  long getFrees();

  /**
   * <code>uint64 LiveObjects = 8;</code>
   */
  long getLiveObjects();

  /**
   * <code>uint64 PauseTotalNs = 9;</code>
   */
  long getPauseTotalNs();

  /**
   * <code>uint32 Uptime = 10;</code>
   */
  int getUptime();
}
