// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/config.proto

package com.xray.transport.internet;

public interface ProxyConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.ProxyConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
