// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/config.proto

package com.xray.transport.internet;

/**
 * <pre>
 * SocketConfig is options to be applied on network sockets.
 * </pre>
 *
 * Protobuf type {@code xray.transport.internet.SocketConfig}
 */
public  final class SocketConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.transport.internet.SocketConfig)
    SocketConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SocketConfig.newBuilder() to construct.
  private SocketConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SocketConfig() {
    tfo_ = 0;
    tproxy_ = 0;
    bindAddress_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SocketConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            mark_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            tfo_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            tproxy_ = rawValue;
            break;
          }
          case 32: {

            receiveOriginalDestAddress_ = input.readBool();
            break;
          }
          case 42: {

            bindAddress_ = input.readBytes();
            break;
          }
          case 48: {

            bindPort_ = input.readUInt32();
            break;
          }
          case 56: {

            acceptProxyProtocol_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xray.transport.internet.Config.internal_static_xray_transport_internet_SocketConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xray.transport.internet.Config.internal_static_xray_transport_internet_SocketConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xray.transport.internet.SocketConfig.class, com.xray.transport.internet.SocketConfig.Builder.class);
  }

  /**
   * Protobuf enum {@code xray.transport.internet.SocketConfig.TCPFastOpenState}
   */
  public enum TCPFastOpenState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * AsIs is to leave the current TFO state as is, unmodified.
     * </pre>
     *
     * <code>AsIs = 0;</code>
     */
    AsIs(0),
    /**
     * <pre>
     * Enable is for enabling TFO explictly.
     * </pre>
     *
     * <code>Enable = 1;</code>
     */
    Enable(1),
    /**
     * <pre>
     * Disable is for disabling TFO explictly.
     * </pre>
     *
     * <code>Disable = 2;</code>
     */
    Disable(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * AsIs is to leave the current TFO state as is, unmodified.
     * </pre>
     *
     * <code>AsIs = 0;</code>
     */
    public static final int AsIs_VALUE = 0;
    /**
     * <pre>
     * Enable is for enabling TFO explictly.
     * </pre>
     *
     * <code>Enable = 1;</code>
     */
    public static final int Enable_VALUE = 1;
    /**
     * <pre>
     * Disable is for disabling TFO explictly.
     * </pre>
     *
     * <code>Disable = 2;</code>
     */
    public static final int Disable_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TCPFastOpenState valueOf(int value) {
      return forNumber(value);
    }

    public static TCPFastOpenState forNumber(int value) {
      switch (value) {
        case 0: return AsIs;
        case 1: return Enable;
        case 2: return Disable;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TCPFastOpenState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TCPFastOpenState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TCPFastOpenState>() {
            public TCPFastOpenState findValueByNumber(int number) {
              return TCPFastOpenState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xray.transport.internet.SocketConfig.getDescriptor().getEnumTypes().get(0);
    }

    private static final TCPFastOpenState[] VALUES = values();

    public static TCPFastOpenState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TCPFastOpenState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xray.transport.internet.SocketConfig.TCPFastOpenState)
  }

  /**
   * Protobuf enum {@code xray.transport.internet.SocketConfig.TProxyMode}
   */
  public enum TProxyMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * TProxy is off.
     * </pre>
     *
     * <code>Off = 0;</code>
     */
    Off(0),
    /**
     * <pre>
     * TProxy mode.
     * </pre>
     *
     * <code>TProxy = 1;</code>
     */
    TProxy(1),
    /**
     * <pre>
     * Redirect mode.
     * </pre>
     *
     * <code>Redirect = 2;</code>
     */
    Redirect(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * TProxy is off.
     * </pre>
     *
     * <code>Off = 0;</code>
     */
    public static final int Off_VALUE = 0;
    /**
     * <pre>
     * TProxy mode.
     * </pre>
     *
     * <code>TProxy = 1;</code>
     */
    public static final int TProxy_VALUE = 1;
    /**
     * <pre>
     * Redirect mode.
     * </pre>
     *
     * <code>Redirect = 2;</code>
     */
    public static final int Redirect_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TProxyMode valueOf(int value) {
      return forNumber(value);
    }

    public static TProxyMode forNumber(int value) {
      switch (value) {
        case 0: return Off;
        case 1: return TProxy;
        case 2: return Redirect;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TProxyMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TProxyMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TProxyMode>() {
            public TProxyMode findValueByNumber(int number) {
              return TProxyMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xray.transport.internet.SocketConfig.getDescriptor().getEnumTypes().get(1);
    }

    private static final TProxyMode[] VALUES = values();

    public static TProxyMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TProxyMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xray.transport.internet.SocketConfig.TProxyMode)
  }

  public static final int MARK_FIELD_NUMBER = 1;
  private int mark_;
  /**
   * <pre>
   * Mark of the connection. If non-zero, the value will be set to SO_MARK.
   * </pre>
   *
   * <code>int32 mark = 1;</code>
   */
  public int getMark() {
    return mark_;
  }

  public static final int TFO_FIELD_NUMBER = 2;
  private int tfo_;
  /**
   * <pre>
   * TFO is the state of TFO settings.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
   */
  public int getTfoValue() {
    return tfo_;
  }
  /**
   * <pre>
   * TFO is the state of TFO settings.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
   */
  public com.xray.transport.internet.SocketConfig.TCPFastOpenState getTfo() {
    @SuppressWarnings("deprecation")
    com.xray.transport.internet.SocketConfig.TCPFastOpenState result = com.xray.transport.internet.SocketConfig.TCPFastOpenState.valueOf(tfo_);
    return result == null ? com.xray.transport.internet.SocketConfig.TCPFastOpenState.UNRECOGNIZED : result;
  }

  public static final int TPROXY_FIELD_NUMBER = 3;
  private int tproxy_;
  /**
   * <pre>
   * TProxy is for enabling TProxy socket option.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
   */
  public int getTproxyValue() {
    return tproxy_;
  }
  /**
   * <pre>
   * TProxy is for enabling TProxy socket option.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
   */
  public com.xray.transport.internet.SocketConfig.TProxyMode getTproxy() {
    @SuppressWarnings("deprecation")
    com.xray.transport.internet.SocketConfig.TProxyMode result = com.xray.transport.internet.SocketConfig.TProxyMode.valueOf(tproxy_);
    return result == null ? com.xray.transport.internet.SocketConfig.TProxyMode.UNRECOGNIZED : result;
  }

  public static final int RECEIVE_ORIGINAL_DEST_ADDRESS_FIELD_NUMBER = 4;
  private boolean receiveOriginalDestAddress_;
  /**
   * <pre>
   * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
   * option. This option is for UDP only.
   * </pre>
   *
   * <code>bool receive_original_dest_address = 4;</code>
   */
  public boolean getReceiveOriginalDestAddress() {
    return receiveOriginalDestAddress_;
  }

  public static final int BIND_ADDRESS_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString bindAddress_;
  /**
   * <code>bytes bind_address = 5;</code>
   */
  public com.google.protobuf.ByteString getBindAddress() {
    return bindAddress_;
  }

  public static final int BIND_PORT_FIELD_NUMBER = 6;
  private int bindPort_;
  /**
   * <code>uint32 bind_port = 6;</code>
   */
  public int getBindPort() {
    return bindPort_;
  }

  public static final int ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER = 7;
  private boolean acceptProxyProtocol_;
  /**
   * <code>bool accept_proxy_protocol = 7;</code>
   */
  public boolean getAcceptProxyProtocol() {
    return acceptProxyProtocol_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mark_ != 0) {
      output.writeInt32(1, mark_);
    }
    if (tfo_ != com.xray.transport.internet.SocketConfig.TCPFastOpenState.AsIs.getNumber()) {
      output.writeEnum(2, tfo_);
    }
    if (tproxy_ != com.xray.transport.internet.SocketConfig.TProxyMode.Off.getNumber()) {
      output.writeEnum(3, tproxy_);
    }
    if (receiveOriginalDestAddress_ != false) {
      output.writeBool(4, receiveOriginalDestAddress_);
    }
    if (!bindAddress_.isEmpty()) {
      output.writeBytes(5, bindAddress_);
    }
    if (bindPort_ != 0) {
      output.writeUInt32(6, bindPort_);
    }
    if (acceptProxyProtocol_ != false) {
      output.writeBool(7, acceptProxyProtocol_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mark_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, mark_);
    }
    if (tfo_ != com.xray.transport.internet.SocketConfig.TCPFastOpenState.AsIs.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, tfo_);
    }
    if (tproxy_ != com.xray.transport.internet.SocketConfig.TProxyMode.Off.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, tproxy_);
    }
    if (receiveOriginalDestAddress_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, receiveOriginalDestAddress_);
    }
    if (!bindAddress_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, bindAddress_);
    }
    if (bindPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, bindPort_);
    }
    if (acceptProxyProtocol_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, acceptProxyProtocol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xray.transport.internet.SocketConfig)) {
      return super.equals(obj);
    }
    com.xray.transport.internet.SocketConfig other = (com.xray.transport.internet.SocketConfig) obj;

    if (getMark()
        != other.getMark()) return false;
    if (tfo_ != other.tfo_) return false;
    if (tproxy_ != other.tproxy_) return false;
    if (getReceiveOriginalDestAddress()
        != other.getReceiveOriginalDestAddress()) return false;
    if (!getBindAddress()
        .equals(other.getBindAddress())) return false;
    if (getBindPort()
        != other.getBindPort()) return false;
    if (getAcceptProxyProtocol()
        != other.getAcceptProxyProtocol()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MARK_FIELD_NUMBER;
    hash = (53 * hash) + getMark();
    hash = (37 * hash) + TFO_FIELD_NUMBER;
    hash = (53 * hash) + tfo_;
    hash = (37 * hash) + TPROXY_FIELD_NUMBER;
    hash = (53 * hash) + tproxy_;
    hash = (37 * hash) + RECEIVE_ORIGINAL_DEST_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReceiveOriginalDestAddress());
    hash = (37 * hash) + BIND_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getBindAddress().hashCode();
    hash = (37 * hash) + BIND_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getBindPort();
    hash = (37 * hash) + ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAcceptProxyProtocol());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xray.transport.internet.SocketConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.transport.internet.SocketConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xray.transport.internet.SocketConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xray.transport.internet.SocketConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xray.transport.internet.SocketConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * SocketConfig is options to be applied on network sockets.
   * </pre>
   *
   * Protobuf type {@code xray.transport.internet.SocketConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.transport.internet.SocketConfig)
      com.xray.transport.internet.SocketConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xray.transport.internet.Config.internal_static_xray_transport_internet_SocketConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xray.transport.internet.Config.internal_static_xray_transport_internet_SocketConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xray.transport.internet.SocketConfig.class, com.xray.transport.internet.SocketConfig.Builder.class);
    }

    // Construct using com.xray.transport.internet.SocketConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mark_ = 0;

      tfo_ = 0;

      tproxy_ = 0;

      receiveOriginalDestAddress_ = false;

      bindAddress_ = com.google.protobuf.ByteString.EMPTY;

      bindPort_ = 0;

      acceptProxyProtocol_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xray.transport.internet.Config.internal_static_xray_transport_internet_SocketConfig_descriptor;
    }

    @java.lang.Override
    public com.xray.transport.internet.SocketConfig getDefaultInstanceForType() {
      return com.xray.transport.internet.SocketConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.xray.transport.internet.SocketConfig build() {
      com.xray.transport.internet.SocketConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xray.transport.internet.SocketConfig buildPartial() {
      com.xray.transport.internet.SocketConfig result = new com.xray.transport.internet.SocketConfig(this);
      result.mark_ = mark_;
      result.tfo_ = tfo_;
      result.tproxy_ = tproxy_;
      result.receiveOriginalDestAddress_ = receiveOriginalDestAddress_;
      result.bindAddress_ = bindAddress_;
      result.bindPort_ = bindPort_;
      result.acceptProxyProtocol_ = acceptProxyProtocol_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xray.transport.internet.SocketConfig) {
        return mergeFrom((com.xray.transport.internet.SocketConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xray.transport.internet.SocketConfig other) {
      if (other == com.xray.transport.internet.SocketConfig.getDefaultInstance()) return this;
      if (other.getMark() != 0) {
        setMark(other.getMark());
      }
      if (other.tfo_ != 0) {
        setTfoValue(other.getTfoValue());
      }
      if (other.tproxy_ != 0) {
        setTproxyValue(other.getTproxyValue());
      }
      if (other.getReceiveOriginalDestAddress() != false) {
        setReceiveOriginalDestAddress(other.getReceiveOriginalDestAddress());
      }
      if (other.getBindAddress() != com.google.protobuf.ByteString.EMPTY) {
        setBindAddress(other.getBindAddress());
      }
      if (other.getBindPort() != 0) {
        setBindPort(other.getBindPort());
      }
      if (other.getAcceptProxyProtocol() != false) {
        setAcceptProxyProtocol(other.getAcceptProxyProtocol());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xray.transport.internet.SocketConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xray.transport.internet.SocketConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int mark_ ;
    /**
     * <pre>
     * Mark of the connection. If non-zero, the value will be set to SO_MARK.
     * </pre>
     *
     * <code>int32 mark = 1;</code>
     */
    public int getMark() {
      return mark_;
    }
    /**
     * <pre>
     * Mark of the connection. If non-zero, the value will be set to SO_MARK.
     * </pre>
     *
     * <code>int32 mark = 1;</code>
     */
    public Builder setMark(int value) {
      
      mark_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Mark of the connection. If non-zero, the value will be set to SO_MARK.
     * </pre>
     *
     * <code>int32 mark = 1;</code>
     */
    public Builder clearMark() {
      
      mark_ = 0;
      onChanged();
      return this;
    }

    private int tfo_ = 0;
    /**
     * <pre>
     * TFO is the state of TFO settings.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     */
    public int getTfoValue() {
      return tfo_;
    }
    /**
     * <pre>
     * TFO is the state of TFO settings.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     */
    public Builder setTfoValue(int value) {
      tfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TFO is the state of TFO settings.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     */
    public com.xray.transport.internet.SocketConfig.TCPFastOpenState getTfo() {
      @SuppressWarnings("deprecation")
      com.xray.transport.internet.SocketConfig.TCPFastOpenState result = com.xray.transport.internet.SocketConfig.TCPFastOpenState.valueOf(tfo_);
      return result == null ? com.xray.transport.internet.SocketConfig.TCPFastOpenState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * TFO is the state of TFO settings.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     */
    public Builder setTfo(com.xray.transport.internet.SocketConfig.TCPFastOpenState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      tfo_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TFO is the state of TFO settings.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     */
    public Builder clearTfo() {
      
      tfo_ = 0;
      onChanged();
      return this;
    }

    private int tproxy_ = 0;
    /**
     * <pre>
     * TProxy is for enabling TProxy socket option.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     */
    public int getTproxyValue() {
      return tproxy_;
    }
    /**
     * <pre>
     * TProxy is for enabling TProxy socket option.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     */
    public Builder setTproxyValue(int value) {
      tproxy_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TProxy is for enabling TProxy socket option.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     */
    public com.xray.transport.internet.SocketConfig.TProxyMode getTproxy() {
      @SuppressWarnings("deprecation")
      com.xray.transport.internet.SocketConfig.TProxyMode result = com.xray.transport.internet.SocketConfig.TProxyMode.valueOf(tproxy_);
      return result == null ? com.xray.transport.internet.SocketConfig.TProxyMode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * TProxy is for enabling TProxy socket option.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     */
    public Builder setTproxy(com.xray.transport.internet.SocketConfig.TProxyMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      tproxy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TProxy is for enabling TProxy socket option.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     */
    public Builder clearTproxy() {
      
      tproxy_ = 0;
      onChanged();
      return this;
    }

    private boolean receiveOriginalDestAddress_ ;
    /**
     * <pre>
     * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     * option. This option is for UDP only.
     * </pre>
     *
     * <code>bool receive_original_dest_address = 4;</code>
     */
    public boolean getReceiveOriginalDestAddress() {
      return receiveOriginalDestAddress_;
    }
    /**
     * <pre>
     * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     * option. This option is for UDP only.
     * </pre>
     *
     * <code>bool receive_original_dest_address = 4;</code>
     */
    public Builder setReceiveOriginalDestAddress(boolean value) {
      
      receiveOriginalDestAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     * option. This option is for UDP only.
     * </pre>
     *
     * <code>bool receive_original_dest_address = 4;</code>
     */
    public Builder clearReceiveOriginalDestAddress() {
      
      receiveOriginalDestAddress_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bindAddress_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bind_address = 5;</code>
     */
    public com.google.protobuf.ByteString getBindAddress() {
      return bindAddress_;
    }
    /**
     * <code>bytes bind_address = 5;</code>
     */
    public Builder setBindAddress(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bindAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bind_address = 5;</code>
     */
    public Builder clearBindAddress() {
      
      bindAddress_ = getDefaultInstance().getBindAddress();
      onChanged();
      return this;
    }

    private int bindPort_ ;
    /**
     * <code>uint32 bind_port = 6;</code>
     */
    public int getBindPort() {
      return bindPort_;
    }
    /**
     * <code>uint32 bind_port = 6;</code>
     */
    public Builder setBindPort(int value) {
      
      bindPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 bind_port = 6;</code>
     */
    public Builder clearBindPort() {
      
      bindPort_ = 0;
      onChanged();
      return this;
    }

    private boolean acceptProxyProtocol_ ;
    /**
     * <code>bool accept_proxy_protocol = 7;</code>
     */
    public boolean getAcceptProxyProtocol() {
      return acceptProxyProtocol_;
    }
    /**
     * <code>bool accept_proxy_protocol = 7;</code>
     */
    public Builder setAcceptProxyProtocol(boolean value) {
      
      acceptProxyProtocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool accept_proxy_protocol = 7;</code>
     */
    public Builder clearAcceptProxyProtocol() {
      
      acceptProxyProtocol_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.transport.internet.SocketConfig)
  }

  // @@protoc_insertion_point(class_scope:xray.transport.internet.SocketConfig)
  private static final com.xray.transport.internet.SocketConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xray.transport.internet.SocketConfig();
  }

  public static com.xray.transport.internet.SocketConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SocketConfig>
      PARSER = new com.google.protobuf.AbstractParser<SocketConfig>() {
    @java.lang.Override
    public SocketConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SocketConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SocketConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SocketConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xray.transport.internet.SocketConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

