// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/config.proto

package com.xray.transport.internet;

public interface SocketConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.SocketConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Mark of the connection. If non-zero, the value will be set to SO_MARK.
   * </pre>
   *
   * <code>int32 mark = 1;</code>
   */
  int getMark();

  /**
   * <pre>
   * TFO is the state of TFO settings.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
   */
  int getTfoValue();
  /**
   * <pre>
   * TFO is the state of TFO settings.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
   */
  com.xray.transport.internet.SocketConfig.TCPFastOpenState getTfo();

  /**
   * <pre>
   * TProxy is for enabling TProxy socket option.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
   */
  int getTproxyValue();
  /**
   * <pre>
   * TProxy is for enabling TProxy socket option.
   * </pre>
   *
   * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
   */
  com.xray.transport.internet.SocketConfig.TProxyMode getTproxy();

  /**
   * <pre>
   * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
   * option. This option is for UDP only.
   * </pre>
   *
   * <code>bool receive_original_dest_address = 4;</code>
   */
  boolean getReceiveOriginalDestAddress();

  /**
   * <code>bytes bind_address = 5;</code>
   */
  com.google.protobuf.ByteString getBindAddress();

  /**
   * <code>uint32 bind_port = 6;</code>
   */
  int getBindPort();

  /**
   * <code>bool accept_proxy_protocol = 7;</code>
   */
  boolean getAcceptProxyProtocol();
}
