// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/config.proto

package com.xray.transport.internet;

public interface TransportConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.TransportConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Type of network that this settings supports.
   * Deprecated. Use the string form below.
   * </pre>
   *
   * <code>.xray.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated int getProtocolValue();
  /**
   * <pre>
   * Type of network that this settings supports.
   * Deprecated. Use the string form below.
   * </pre>
   *
   * <code>.xray.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.xray.transport.internet.TransportProtocol getProtocol();

  /**
   * <pre>
   * Type of network that this settings supports.
   * </pre>
   *
   * <code>string protocol_name = 3;</code>
   */
  java.lang.String getProtocolName();
  /**
   * <pre>
   * Type of network that this settings supports.
   * </pre>
   *
   * <code>string protocol_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getProtocolNameBytes();

  /**
   * <pre>
   * Specific settings. Must be of the transports.
   * </pre>
   *
   * <code>.xray.common.serial.TypedMessage settings = 2;</code>
   */
  boolean hasSettings();
  /**
   * <pre>
   * Specific settings. Must be of the transports.
   * </pre>
   *
   * <code>.xray.common.serial.TypedMessage settings = 2;</code>
   */
  com.xray.common.serial.TypedMessage getSettings();
  /**
   * <pre>
   * Specific settings. Must be of the transports.
   * </pre>
   *
   * <code>.xray.common.serial.TypedMessage settings = 2;</code>
   */
  com.xray.common.serial.TypedMessageOrBuilder getSettingsOrBuilder();
}
