// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/tls/config.proto

package com.xray.transport.internet.tls;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_tls_Certificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_tls_Certificate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_tls_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_tls_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#transport/internet/tls/config.proto\022\033x" +
      "ray.transport.internet.tls\"\313\001\n\013Certifica" +
      "te\022\023\n\013certificate\030\001 \001(\014\022\013\n\003key\030\002 \001(\014\022=\n\005" +
      "usage\030\003 \001(\0162..xray.transport.internet.tl" +
      "s.Certificate.Usage\022\025\n\rocsp_stapling\030\004 \001" +
      "(\003\"D\n\005Usage\022\020\n\014ENCIPHERMENT\020\000\022\024\n\020AUTHORI" +
      "TY_VERIFY\020\001\022\023\n\017AUTHORITY_ISSUE\020\002\"\261\002\n\006Con" +
      "fig\022\026\n\016allow_insecure\030\001 \001(\010\022=\n\013certifica" +
      "te\030\002 \003(\0132(.xray.transport.internet.tls.C" +
      "ertificate\022\023\n\013server_name\030\003 \001(\t\022\025\n\rnext_" +
      "protocol\030\004 \003(\t\022!\n\031enable_session_resumpt" +
      "ion\030\005 \001(\010\022\033\n\023disable_system_root\030\006 \001(\010\022\023" +
      "\n\013min_version\030\007 \001(\t\022\023\n\013max_version\030\010 \001(\t" +
      "\022\025\n\rcipher_suites\030\t \001(\t\022#\n\033prefer_server" +
      "_cipher_suites\030\n \001(\010Bs\n\037com.xray.transpo" +
      "rt.internet.tlsP\001Z0github.com/xtls/xray-" +
      "core/transport/internet/tls\252\002\033Xray.Trans" +
      "port.Internet.Tlsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_xray_transport_internet_tls_Certificate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_transport_internet_tls_Certificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_tls_Certificate_descriptor,
        new java.lang.String[] { "Certificate", "Key", "Usage", "OcspStapling", });
    internal_static_xray_transport_internet_tls_Config_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_transport_internet_tls_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_tls_Config_descriptor,
        new java.lang.String[] { "AllowInsecure", "Certificate", "ServerName", "NextProtocol", "EnableSessionResumption", "DisableSystemRoot", "MinVersion", "MaxVersion", "CipherSuites", "PreferServerCipherSuites", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
