// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/reverse/config.proto

package com.xray.proxy.reverse;

public interface ControlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.reverse.Control)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.app.reverse.Control.State state = 1;</code>
   */
  int getStateValue();
  /**
   * <code>.xray.app.reverse.Control.State state = 1;</code>
   */
  com.xray.proxy.reverse.Control.State getState();

  /**
   * <code>bytes random = 99;</code>
   */
  com.google.protobuf.ByteString getRandom();
}
