// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/reverse/config.proto

package com.xray.proxy.reverse;

public interface PortalConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.reverse.PortalConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string domain = 2;</code>
   */
  java.lang.String getDomain();
  /**
   * <code>string domain = 2;</code>
   */
  com.google.protobuf.ByteString
      getDomainBytes();
}
