// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/mtproto/config.proto

package com.xray.proxy.mtproto;

public interface ClientConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.mtproto.ClientConfig)
    com.google.protobuf.MessageOrBuilder {
}
