// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/mtproto/config.proto

package com.xray.proxy.mtproto;

public interface ServerConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.mtproto.ServerConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User is a list of users that allowed to connect to this inbound.
   * Although this is a repeated field, only the first user is effective for
   * now.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  java.util.List<com.xray.common.protocol.User> 
      getUserList();
  /**
   * <pre>
   * User is a list of users that allowed to connect to this inbound.
   * Although this is a repeated field, only the first user is effective for
   * now.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  com.xray.common.protocol.User getUser(int index);
  /**
   * <pre>
   * User is a list of users that allowed to connect to this inbound.
   * Although this is a repeated field, only the first user is effective for
   * now.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  int getUserCount();
  /**
   * <pre>
   * User is a list of users that allowed to connect to this inbound.
   * Although this is a repeated field, only the first user is effective for
   * now.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  java.util.List<? extends com.xray.common.protocol.UserOrBuilder> 
      getUserOrBuilderList();
  /**
   * <pre>
   * User is a list of users that allowed to connect to this inbound.
   * Although this is a repeated field, only the first user is effective for
   * now.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.User user = 1;</code>
   */
  com.xray.common.protocol.UserOrBuilder getUserOrBuilder(
      int index);
}
