// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/config.proto

package com.xray.transport;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026transport/config.proto\022\016xray.transport" +
      "\032\037transport/internet/config.proto\"R\n\006Con" +
      "fig\022D\n\022transport_settings\030\001 \003(\0132(.xray.t" +
      "ransport.internet.TransportConfig:\002\030\001BL\n" +
      "\022com.xray.transportP\001Z#github.com/xtls/x" +
      "ray-core/transport\252\002\016Xray.Transportb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xray.transport.internet.Config.getDescriptor(),
        }, assigner);
    internal_static_xray_transport_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_transport_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_Config_descriptor,
        new java.lang.String[] { "TransportSettings", });
    com.xray.transport.internet.Config.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
