// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/grpc/config.proto

package xray.transport.internet.grpc.encoding;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xray.transport.internet.grpc.encoding.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>string service_name = 2;</code>
     * @return The serviceName.
     */
    java.lang.String getServiceName();
    /**
     * <code>string service_name = 2;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>bool multi_mode = 3;</code>
     * @return The multiMode.
     */
    boolean getMultiMode();

    /**
     * <code>int32 idle_timeout = 4;</code>
     * @return The idleTimeout.
     */
    int getIdleTimeout();

    /**
     * <code>int32 health_check_timeout = 5;</code>
     * @return The healthCheckTimeout.
     */
    int getHealthCheckTimeout();

    /**
     * <code>bool permit_without_stream = 6;</code>
     * @return The permitWithoutStream.
     */
    boolean getPermitWithoutStream();

    /**
     * <code>int32 initial_windows_size = 7;</code>
     * @return The initialWindowsSize.
     */
    int getInitialWindowsSize();

    /**
     * <code>string user_agent = 8;</code>
     * @return The userAgent.
     */
    java.lang.String getUserAgent();
    /**
     * <code>string user_agent = 8;</code>
     * @return The bytes for userAgent.
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();
  }
  /**
   * Protobuf type {@code xray.transport.internet.grpc.encoding.Config}
   */
  public static final class Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xray.transport.internet.grpc.encoding.Config)
      ConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Config() {
      host_ = "";
      serviceName_ = "";
      userAgent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Config();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xray.transport.internet.grpc.encoding.ConfigOuterClass.internal_static_xray_transport_internet_grpc_encoding_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xray.transport.internet.grpc.encoding.ConfigOuterClass.internal_static_xray_transport_internet_grpc_encoding_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xray.transport.internet.grpc.encoding.ConfigOuterClass.Config.class, xray.transport.internet.grpc.encoding.ConfigOuterClass.Config.Builder.class);
    }

    public static final int HOST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object host_ = "";
    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceName_ = "";
    /**
     * <code>string service_name = 2;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string service_name = 2;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MULTI_MODE_FIELD_NUMBER = 3;
    private boolean multiMode_ = false;
    /**
     * <code>bool multi_mode = 3;</code>
     * @return The multiMode.
     */
    @java.lang.Override
    public boolean getMultiMode() {
      return multiMode_;
    }

    public static final int IDLE_TIMEOUT_FIELD_NUMBER = 4;
    private int idleTimeout_ = 0;
    /**
     * <code>int32 idle_timeout = 4;</code>
     * @return The idleTimeout.
     */
    @java.lang.Override
    public int getIdleTimeout() {
      return idleTimeout_;
    }

    public static final int HEALTH_CHECK_TIMEOUT_FIELD_NUMBER = 5;
    private int healthCheckTimeout_ = 0;
    /**
     * <code>int32 health_check_timeout = 5;</code>
     * @return The healthCheckTimeout.
     */
    @java.lang.Override
    public int getHealthCheckTimeout() {
      return healthCheckTimeout_;
    }

    public static final int PERMIT_WITHOUT_STREAM_FIELD_NUMBER = 6;
    private boolean permitWithoutStream_ = false;
    /**
     * <code>bool permit_without_stream = 6;</code>
     * @return The permitWithoutStream.
     */
    @java.lang.Override
    public boolean getPermitWithoutStream() {
      return permitWithoutStream_;
    }

    public static final int INITIAL_WINDOWS_SIZE_FIELD_NUMBER = 7;
    private int initialWindowsSize_ = 0;
    /**
     * <code>int32 initial_windows_size = 7;</code>
     * @return The initialWindowsSize.
     */
    @java.lang.Override
    public int getInitialWindowsSize() {
      return initialWindowsSize_;
    }

    public static final int USER_AGENT_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userAgent_ = "";
    /**
     * <code>string user_agent = 8;</code>
     * @return The userAgent.
     */
    @java.lang.Override
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      }
    }
    /**
     * <code>string user_agent = 8;</code>
     * @return The bytes for userAgent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
      }
      if (multiMode_ != false) {
        output.writeBool(3, multiMode_);
      }
      if (idleTimeout_ != 0) {
        output.writeInt32(4, idleTimeout_);
      }
      if (healthCheckTimeout_ != 0) {
        output.writeInt32(5, healthCheckTimeout_);
      }
      if (permitWithoutStream_ != false) {
        output.writeBool(6, permitWithoutStream_);
      }
      if (initialWindowsSize_ != 0) {
        output.writeInt32(7, initialWindowsSize_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userAgent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userAgent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
      }
      if (multiMode_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, multiMode_);
      }
      if (idleTimeout_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, idleTimeout_);
      }
      if (healthCheckTimeout_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, healthCheckTimeout_);
      }
      if (permitWithoutStream_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, permitWithoutStream_);
      }
      if (initialWindowsSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, initialWindowsSize_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userAgent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userAgent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xray.transport.internet.grpc.encoding.ConfigOuterClass.Config)) {
        return super.equals(obj);
      }
      xray.transport.internet.grpc.encoding.ConfigOuterClass.Config other = (xray.transport.internet.grpc.encoding.ConfigOuterClass.Config) obj;

      if (!getHost()
          .equals(other.getHost())) return false;
      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (getMultiMode()
          != other.getMultiMode()) return false;
      if (getIdleTimeout()
          != other.getIdleTimeout()) return false;
      if (getHealthCheckTimeout()
          != other.getHealthCheckTimeout()) return false;
      if (getPermitWithoutStream()
          != other.getPermitWithoutStream()) return false;
      if (getInitialWindowsSize()
          != other.getInitialWindowsSize()) return false;
      if (!getUserAgent()
          .equals(other.getUserAgent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + MULTI_MODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMultiMode());
      hash = (37 * hash) + IDLE_TIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + getIdleTimeout();
      hash = (37 * hash) + HEALTH_CHECK_TIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + getHealthCheckTimeout();
      hash = (37 * hash) + PERMIT_WITHOUT_STREAM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPermitWithoutStream());
      hash = (37 * hash) + INITIAL_WINDOWS_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getInitialWindowsSize();
      hash = (37 * hash) + USER_AGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAgent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xray.transport.internet.grpc.encoding.ConfigOuterClass.Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xray.transport.internet.grpc.encoding.Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xray.transport.internet.grpc.encoding.Config)
        xray.transport.internet.grpc.encoding.ConfigOuterClass.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xray.transport.internet.grpc.encoding.ConfigOuterClass.internal_static_xray_transport_internet_grpc_encoding_Config_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xray.transport.internet.grpc.encoding.ConfigOuterClass.internal_static_xray_transport_internet_grpc_encoding_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xray.transport.internet.grpc.encoding.ConfigOuterClass.Config.class, xray.transport.internet.grpc.encoding.ConfigOuterClass.Config.Builder.class);
      }

      // Construct using xray.transport.internet.grpc.encoding.ConfigOuterClass.Config.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        host_ = "";
        serviceName_ = "";
        multiMode_ = false;
        idleTimeout_ = 0;
        healthCheckTimeout_ = 0;
        permitWithoutStream_ = false;
        initialWindowsSize_ = 0;
        userAgent_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xray.transport.internet.grpc.encoding.ConfigOuterClass.internal_static_xray_transport_internet_grpc_encoding_Config_descriptor;
      }

      @java.lang.Override
      public xray.transport.internet.grpc.encoding.ConfigOuterClass.Config getDefaultInstanceForType() {
        return xray.transport.internet.grpc.encoding.ConfigOuterClass.Config.getDefaultInstance();
      }

      @java.lang.Override
      public xray.transport.internet.grpc.encoding.ConfigOuterClass.Config build() {
        xray.transport.internet.grpc.encoding.ConfigOuterClass.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xray.transport.internet.grpc.encoding.ConfigOuterClass.Config buildPartial() {
        xray.transport.internet.grpc.encoding.ConfigOuterClass.Config result = new xray.transport.internet.grpc.encoding.ConfigOuterClass.Config(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(xray.transport.internet.grpc.encoding.ConfigOuterClass.Config result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.host_ = host_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serviceName_ = serviceName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.multiMode_ = multiMode_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.idleTimeout_ = idleTimeout_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.healthCheckTimeout_ = healthCheckTimeout_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.permitWithoutStream_ = permitWithoutStream_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.initialWindowsSize_ = initialWindowsSize_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.userAgent_ = userAgent_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xray.transport.internet.grpc.encoding.ConfigOuterClass.Config) {
          return mergeFrom((xray.transport.internet.grpc.encoding.ConfigOuterClass.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xray.transport.internet.grpc.encoding.ConfigOuterClass.Config other) {
        if (other == xray.transport.internet.grpc.encoding.ConfigOuterClass.Config.getDefaultInstance()) return this;
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getMultiMode() != false) {
          setMultiMode(other.getMultiMode());
        }
        if (other.getIdleTimeout() != 0) {
          setIdleTimeout(other.getIdleTimeout());
        }
        if (other.getHealthCheckTimeout() != 0) {
          setHealthCheckTimeout(other.getHealthCheckTimeout());
        }
        if (other.getPermitWithoutStream() != false) {
          setPermitWithoutStream(other.getPermitWithoutStream());
        }
        if (other.getInitialWindowsSize() != 0) {
          setInitialWindowsSize(other.getInitialWindowsSize());
        }
        if (!other.getUserAgent().isEmpty()) {
          userAgent_ = other.userAgent_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                host_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                serviceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                multiMode_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                idleTimeout_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                healthCheckTimeout_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                permitWithoutStream_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                initialWindowsSize_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                userAgent_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 1;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 1;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        host_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        host_ = getDefaultInstance().getHost();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string host = 1;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        host_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string service_name = 2;</code>
       * @return The serviceName.
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string service_name = 2;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string service_name = 2;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string service_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {
        serviceName_ = getDefaultInstance().getServiceName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string service_name = 2;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean multiMode_ ;
      /**
       * <code>bool multi_mode = 3;</code>
       * @return The multiMode.
       */
      @java.lang.Override
      public boolean getMultiMode() {
        return multiMode_;
      }
      /**
       * <code>bool multi_mode = 3;</code>
       * @param value The multiMode to set.
       * @return This builder for chaining.
       */
      public Builder setMultiMode(boolean value) {
        
        multiMode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool multi_mode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMultiMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        multiMode_ = false;
        onChanged();
        return this;
      }

      private int idleTimeout_ ;
      /**
       * <code>int32 idle_timeout = 4;</code>
       * @return The idleTimeout.
       */
      @java.lang.Override
      public int getIdleTimeout() {
        return idleTimeout_;
      }
      /**
       * <code>int32 idle_timeout = 4;</code>
       * @param value The idleTimeout to set.
       * @return This builder for chaining.
       */
      public Builder setIdleTimeout(int value) {
        
        idleTimeout_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idle_timeout = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdleTimeout() {
        bitField0_ = (bitField0_ & ~0x00000008);
        idleTimeout_ = 0;
        onChanged();
        return this;
      }

      private int healthCheckTimeout_ ;
      /**
       * <code>int32 health_check_timeout = 5;</code>
       * @return The healthCheckTimeout.
       */
      @java.lang.Override
      public int getHealthCheckTimeout() {
        return healthCheckTimeout_;
      }
      /**
       * <code>int32 health_check_timeout = 5;</code>
       * @param value The healthCheckTimeout to set.
       * @return This builder for chaining.
       */
      public Builder setHealthCheckTimeout(int value) {
        
        healthCheckTimeout_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 health_check_timeout = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHealthCheckTimeout() {
        bitField0_ = (bitField0_ & ~0x00000010);
        healthCheckTimeout_ = 0;
        onChanged();
        return this;
      }

      private boolean permitWithoutStream_ ;
      /**
       * <code>bool permit_without_stream = 6;</code>
       * @return The permitWithoutStream.
       */
      @java.lang.Override
      public boolean getPermitWithoutStream() {
        return permitWithoutStream_;
      }
      /**
       * <code>bool permit_without_stream = 6;</code>
       * @param value The permitWithoutStream to set.
       * @return This builder for chaining.
       */
      public Builder setPermitWithoutStream(boolean value) {
        
        permitWithoutStream_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bool permit_without_stream = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPermitWithoutStream() {
        bitField0_ = (bitField0_ & ~0x00000020);
        permitWithoutStream_ = false;
        onChanged();
        return this;
      }

      private int initialWindowsSize_ ;
      /**
       * <code>int32 initial_windows_size = 7;</code>
       * @return The initialWindowsSize.
       */
      @java.lang.Override
      public int getInitialWindowsSize() {
        return initialWindowsSize_;
      }
      /**
       * <code>int32 initial_windows_size = 7;</code>
       * @param value The initialWindowsSize to set.
       * @return This builder for chaining.
       */
      public Builder setInitialWindowsSize(int value) {
        
        initialWindowsSize_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 initial_windows_size = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearInitialWindowsSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        initialWindowsSize_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>string user_agent = 8;</code>
       * @return The userAgent.
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_agent = 8;</code>
       * @return The bytes for userAgent.
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_agent = 8;</code>
       * @param value The userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userAgent_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string user_agent = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserAgent() {
        userAgent_ = getDefaultInstance().getUserAgent();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string user_agent = 8;</code>
       * @param value The bytes for userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userAgent_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xray.transport.internet.grpc.encoding.Config)
    }

    // @@protoc_insertion_point(class_scope:xray.transport.internet.grpc.encoding.Config)
    private static final xray.transport.internet.grpc.encoding.ConfigOuterClass.Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xray.transport.internet.grpc.encoding.ConfigOuterClass.Config();
    }

    public static xray.transport.internet.grpc.encoding.ConfigOuterClass.Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Config>
        PARSER = new com.google.protobuf.AbstractParser<Config>() {
      @java.lang.Override
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xray.transport.internet.grpc.encoding.ConfigOuterClass.Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_grpc_encoding_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_grpc_encoding_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$transport/internet/grpc/config.proto\022%" +
      "xray.transport.internet.grpc.encoding\"\305\001" +
      "\n\006Config\022\014\n\004host\030\001 \001(\t\022\024\n\014service_name\030\002" +
      " \001(\t\022\022\n\nmulti_mode\030\003 \001(\010\022\024\n\014idle_timeout" +
      "\030\004 \001(\005\022\034\n\024health_check_timeout\030\005 \001(\005\022\035\n\025" +
      "permit_without_stream\030\006 \001(\010\022\034\n\024initial_w" +
      "indows_size\030\007 \001(\005\022\022\n\nuser_agent\030\010 \001(\tB3Z" +
      "1github.com/xtls/xray-core/transport/int" +
      "ernet/grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xray_transport_internet_grpc_encoding_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_transport_internet_grpc_encoding_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_grpc_encoding_Config_descriptor,
        new java.lang.String[] { "Host", "ServiceName", "MultiMode", "IdleTimeout", "HealthCheckTimeout", "PermitWithoutStream", "InitialWindowsSize", "UserAgent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
