// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/policy/config.proto

package com.xray.app.policy;

public interface PolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.policy.Policy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.app.policy.Policy.Timeout timeout = 1;</code>
   */
  boolean hasTimeout();
  /**
   * <code>.xray.app.policy.Policy.Timeout timeout = 1;</code>
   */
  com.xray.app.policy.Policy.Timeout getTimeout();
  /**
   * <code>.xray.app.policy.Policy.Timeout timeout = 1;</code>
   */
  com.xray.app.policy.Policy.TimeoutOrBuilder getTimeoutOrBuilder();

  /**
   * <code>.xray.app.policy.Policy.Stats stats = 2;</code>
   */
  boolean hasStats();
  /**
   * <code>.xray.app.policy.Policy.Stats stats = 2;</code>
   */
  com.xray.app.policy.Policy.Stats getStats();
  /**
   * <code>.xray.app.policy.Policy.Stats stats = 2;</code>
   */
  com.xray.app.policy.Policy.StatsOrBuilder getStatsOrBuilder();

  /**
   * <code>.xray.app.policy.Policy.Buffer buffer = 3;</code>
   */
  boolean hasBuffer();
  /**
   * <code>.xray.app.policy.Policy.Buffer buffer = 3;</code>
   */
  com.xray.app.policy.Policy.Buffer getBuffer();
  /**
   * <code>.xray.app.policy.Policy.Buffer buffer = 3;</code>
   */
  com.xray.app.policy.Policy.BufferOrBuilder getBufferOrBuilder();
}
