// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/policy/config.proto

package com.xray.app.policy;

public interface SystemPolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.policy.SystemPolicy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.app.policy.SystemPolicy.Stats stats = 1;</code>
   */
  boolean hasStats();
  /**
   * <code>.xray.app.policy.SystemPolicy.Stats stats = 1;</code>
   */
  com.xray.app.policy.SystemPolicy.Stats getStats();
  /**
   * <code>.xray.app.policy.SystemPolicy.Stats stats = 1;</code>
   */
  com.xray.app.policy.SystemPolicy.StatsOrBuilder getStatsOrBuilder();
}
