// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/blackhole/config.proto

package com.xray.proxy.blackhole;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.blackhole.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.common.serial.TypedMessage response = 1;</code>
   */
  boolean hasResponse();
  /**
   * <code>.xray.common.serial.TypedMessage response = 1;</code>
   */
  com.xray.common.serial.TypedMessage getResponse();
  /**
   * <code>.xray.common.serial.TypedMessage response = 1;</code>
   */
  com.xray.common.serial.TypedMessageOrBuilder getResponseOrBuilder();
}
