// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/socks/config.proto

package com.xray.proxy.socks;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.socks.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
