// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/xtls/config.proto

package com.xray.transport.internet.xtls;

public interface CertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.xtls.Certificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * TLS certificate in x509 format.
   * </pre>
   *
   * <code>bytes certificate = 1;</code>
   */
  com.google.protobuf.ByteString getCertificate();

  /**
   * <pre>
   * TLS key in x509 format.
   * </pre>
   *
   * <code>bytes key = 2;</code>
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>.xray.transport.internet.xtls.Certificate.Usage usage = 3;</code>
   */
  int getUsageValue();
  /**
   * <code>.xray.transport.internet.xtls.Certificate.Usage usage = 3;</code>
   */
  com.xray.transport.internet.xtls.Certificate.Usage getUsage();

  /**
   * <code>int64 ocsp_stapling = 4;</code>
   */
  long getOcspStapling();
}
