// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/xtls/config.proto

package com.xray.transport.internet.xtls;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.xtls.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether or not to allow self-signed certificates.
   * </pre>
   *
   * <code>bool allow_insecure = 1;</code>
   */
  boolean getAllowInsecure();

  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.xtls.Certificate certificate = 2;</code>
   */
  java.util.List<com.xray.transport.internet.xtls.Certificate> 
      getCertificateList();
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.xtls.Certificate certificate = 2;</code>
   */
  com.xray.transport.internet.xtls.Certificate getCertificate(int index);
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.xtls.Certificate certificate = 2;</code>
   */
  int getCertificateCount();
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.xtls.Certificate certificate = 2;</code>
   */
  java.util.List<? extends com.xray.transport.internet.xtls.CertificateOrBuilder> 
      getCertificateOrBuilderList();
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.xtls.Certificate certificate = 2;</code>
   */
  com.xray.transport.internet.xtls.CertificateOrBuilder getCertificateOrBuilder(
      int index);

  /**
   * <pre>
   * Override server name.
   * </pre>
   *
   * <code>string server_name = 3;</code>
   */
  java.lang.String getServerName();
  /**
   * <pre>
   * Override server name.
   * </pre>
   *
   * <code>string server_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   */
  java.util.List<java.lang.String>
      getNextProtocolList();
  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   */
  int getNextProtocolCount();
  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   */
  java.lang.String getNextProtocol(int index);
  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   */
  com.google.protobuf.ByteString
      getNextProtocolBytes(int index);

  /**
   * <pre>
   * Whether or not to enable session (ticket) resumption.
   * </pre>
   *
   * <code>bool enable_session_resumption = 5;</code>
   */
  boolean getEnableSessionResumption();

  /**
   * <pre>
   * If true, root certificates on the system will not be loaded for
   * verification.
   * </pre>
   *
   * <code>bool disable_system_root = 6;</code>
   */
  boolean getDisableSystemRoot();

  /**
   * <pre>
   * The minimum TLS version.
   * </pre>
   *
   * <code>string min_version = 7;</code>
   */
  java.lang.String getMinVersion();
  /**
   * <pre>
   * The minimum TLS version.
   * </pre>
   *
   * <code>string min_version = 7;</code>
   */
  com.google.protobuf.ByteString
      getMinVersionBytes();

  /**
   * <pre>
   * The maximum TLS version.
   * </pre>
   *
   * <code>string max_version = 8;</code>
   */
  java.lang.String getMaxVersion();
  /**
   * <pre>
   * The maximum TLS version.
   * </pre>
   *
   * <code>string max_version = 8;</code>
   */
  com.google.protobuf.ByteString
      getMaxVersionBytes();

  /**
   * <pre>
   * Specify cipher suites, except for TLS 1.3.
   * </pre>
   *
   * <code>string cipher_suites = 9;</code>
   */
  java.lang.String getCipherSuites();
  /**
   * <pre>
   * Specify cipher suites, except for TLS 1.3.
   * </pre>
   *
   * <code>string cipher_suites = 9;</code>
   */
  com.google.protobuf.ByteString
      getCipherSuitesBytes();

  /**
   * <pre>
   * Whether the server selects its most preferred ciphersuite.
   * </pre>
   *
   * <code>bool prefer_server_cipher_suites = 10;</code>
   */
  boolean getPreferServerCipherSuites();
}
