// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/xtls/config.proto

package com.xray.transport.internet.xtls;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_xtls_Certificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_xtls_Certificate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_xtls_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_xtls_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$transport/internet/xtls/config.proto\022\034" +
      "xray.transport.internet.xtls\"\314\001\n\013Certifi" +
      "cate\022\023\n\013certificate\030\001 \001(\014\022\013\n\003key\030\002 \001(\014\022>" +
      "\n\005usage\030\003 \001(\0162/.xray.transport.internet." +
      "xtls.Certificate.Usage\022\025\n\rocsp_stapling\030" +
      "\004 \001(\003\"D\n\005Usage\022\020\n\014ENCIPHERMENT\020\000\022\024\n\020AUTH" +
      "ORITY_VERIFY\020\001\022\023\n\017AUTHORITY_ISSUE\020\002\"\262\002\n\006" +
      "Config\022\026\n\016allow_insecure\030\001 \001(\010\022>\n\013certif" +
      "icate\030\002 \003(\0132).xray.transport.internet.xt" +
      "ls.Certificate\022\023\n\013server_name\030\003 \001(\t\022\025\n\rn" +
      "ext_protocol\030\004 \003(\t\022!\n\031enable_session_res" +
      "umption\030\005 \001(\010\022\033\n\023disable_system_root\030\006 \001" +
      "(\010\022\023\n\013min_version\030\007 \001(\t\022\023\n\013max_version\030\010" +
      " \001(\t\022\025\n\rcipher_suites\030\t \001(\t\022#\n\033prefer_se" +
      "rver_cipher_suites\030\n \001(\010Bv\n com.xray.tra" +
      "nsport.internet.xtlsP\001Z1github.com/xtls/" +
      "xray-core/transport/internet/xtls\252\002\034Xray" +
      ".Transport.Internet.Xtlsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_xray_transport_internet_xtls_Certificate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_transport_internet_xtls_Certificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_xtls_Certificate_descriptor,
        new java.lang.String[] { "Certificate", "Key", "Usage", "OcspStapling", });
    internal_static_xray_transport_internet_xtls_Config_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_transport_internet_xtls_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_xtls_Config_descriptor,
        new java.lang.String[] { "AllowInsecure", "Certificate", "ServerName", "NextProtocol", "EnableSessionResumption", "DisableSystemRoot", "MinVersion", "MaxVersion", "CipherSuites", "PreferServerCipherSuites", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
