// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/protocol/headers.proto

package com.xray.common.protocol;

public interface SecurityConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.common.protocol.SecurityConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.common.protocol.SecurityType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.xray.common.protocol.SecurityType type = 1;</code>
   */
  com.xray.common.protocol.SecurityType getType();
}
