// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/shadowsocks/config.proto

package com.xray.proxy.shadowsocks;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.shadowsocks.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>.xray.proxy.shadowsocks.CipherType cipher_type = 2;</code>
   */
  int getCipherTypeValue();
  /**
   * <code>.xray.proxy.shadowsocks.CipherType cipher_type = 2;</code>
   */
  com.xray.proxy.shadowsocks.CipherType getCipherType();
}
