// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/shadowsocks/config.proto

package com.xray.proxy.shadowsocks;

public interface ServerConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.shadowsocks.ServerConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.common.protocol.User users = 1;</code>
   */
  java.util.List<com.xray.common.protocol.User> 
      getUsersList();
  /**
   * <code>repeated .xray.common.protocol.User users = 1;</code>
   */
  com.xray.common.protocol.User getUsers(int index);
  /**
   * <code>repeated .xray.common.protocol.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .xray.common.protocol.User users = 1;</code>
   */
  java.util.List<? extends com.xray.common.protocol.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .xray.common.protocol.User users = 1;</code>
   */
  com.xray.common.protocol.UserOrBuilder getUsersOrBuilder(
      int index);

  /**
   * <code>repeated .xray.common.net.Network network = 2;</code>
   */
  java.util.List<com.xray.common.net.Network> getNetworkList();
  /**
   * <code>repeated .xray.common.net.Network network = 2;</code>
   */
  int getNetworkCount();
  /**
   * <code>repeated .xray.common.net.Network network = 2;</code>
   */
  com.xray.common.net.Network getNetwork(int index);
  /**
   * <code>repeated .xray.common.net.Network network = 2;</code>
   */
  java.util.List<java.lang.Integer>
  getNetworkValueList();
  /**
   * <code>repeated .xray.common.net.Network network = 2;</code>
   */
  int getNetworkValue(int index);
}
