admin:
  #第一次启动时候的账号和密码
  email: admin@admin.com
  password: 123456

proxy:
  #与porxy交互的密码，也是各种token的私钥
  authPassword: '123456'
  subscriptionTemplate: /subscribe/%s?target=%s&type=%s&timestamp=%s&token=%s

email:
  #stmp地址
  host:
  #用户名称
  userName:
  #密码
  password:
  #端口
  port:
  #默认false ,邮件不支持startTls不要开启
  startTlsEnabled: false

  exceedConnections: 你当前的连接数已经超过账号最大限制，当前风险系统自动降低你一半的连接数，并且持续一个小时;如果你在一个小时后，不在触发监控指标，你的账号连接数将恢复。
  vCodeTemplate: '你的验证码为: %s,请在10分钟内使用'
  overdueDate: 你的账号即将于：%s 过期，请留意续费。

logging:
  level:
    root: info
  file:
    name: ./logs/admin.log
  logback:
    rollingpolicy:
      max-history: 7

server:
  port: 9091
  tomcat:
    threads:
      max: 3
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:./admin.db
    username: ''
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.jhl.admin.util.SQLiteDialect
        enable_lazy_load_no_trans: true
        format_sql: ''
        show_sql: false

client:
  supportList:
    - value: shadowrocket
      label: Shadowrocket
    - value: clash
      label: Clash
    - value: clash2
      label: Clash Premium
    - value: clash3
      label: Clash.Meta
    - value: loon
      label: Loon
    - value: surge
      label: Surge 4
    - value: quanx
      label: Quantumult X