product: false
admin:
  #第一次启动时候的账号和密码
  email: admin@admin.com
  password: 123456

proxy:
  #与porxy交互的密码，也是各种token的私钥
  authPassword: '123456'
  subscriptionTemplate: /subscribe/%s?target=%s&type=%s&timestamp=%s&token=%s

email:
  #stmp地址
  host:
  #用户名称
  userName:
  #密码
  password:
  #端口
  port:
  #默认false ,邮件不支持startTls不要开启
  startTlsEnabled: false

  exceedConnections: 你当前的连接数已经超过账号最大限制，当前风险系统自动降低你一半的连接数，并且持续一个小时;如果你在一个小时后，不在触发监控指标，你的账号连接数将恢复。
  vCodeTemplate: '你的验证码为: %s,请在10分钟内使用'
  overdueDate: 你的账号即将于：%s 过期，请留意续费。

logging:
  level:
    root: info
  file:
    name: ./logs/admin.log
  logback:
    rollingpolicy:
      max-history: 7

server:
  port: 9091
  tomcat:
    threads:
      max: 3
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:./admin.db
    username: ''
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.fun90.admin.util.SQLiteDialect
        enable_lazy_load_no_trans: true
        format_sql: ''
        show_sql: false

client:
  supportProtocols:
    - value: vmess
      label: VMess
    - value: trojan
      label: Trojan
    - value: vless
      label: VLESS
    - value: hysteria
      label: Hysteria
    - value: hysteria2
      label: Hysteria2
  supportList:
    #- value: shadowrocket
    #  label: Shadowrocket
#    - value: clash
#      label: Clash
    - value: clash2
      label: Clash Premium
    - value: clash3
      label: Shadowrocket/Clash.Meta
      protocols:
        - vmess
        - trojan
        - vless
        - hysteria
        - hysteria2
    - value: loon
      label: Loon
      protocols:
        - vmess
        - trojan
    - value: surge
      label: Surge 4
      protocols:
        - vmess
        - trojan
    - value: quanx
      label: Quantumult X
      protocols:
        - vmess
        - trojan

rules-source:
  url-map: {
    "direct": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/direct.txt",
    "cncidr": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/cncidr.txt",
    "private": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/private.txt",
    "tld-not-cn": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/tld-not-cn.txt",
    "gfw": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt",
    "greatfire": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/greatfire.txt",
    "proxy": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/proxy.txt",
    "apple": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/apple.txt",
    "icloud": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/icloud.txt",
    "telegramcidr": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/telegramcidr.txt",
    "reject": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/reject.txt",
    "advertisinglite": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingLite/AdvertisingLite_Resolve.list",
    "advertisinglitedomain": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingLite/AdvertisingLite_Domain.list",
    "banprogramad": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list",
    "google": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google_Resolve.list",
    "microsoft": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list",
    "paypal": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PayPal/PayPal.list",
    "amazon": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Amazon/Amazon.list",
    "youtube": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube_Resolve.list"
  }