admin:
  #第一次启动时候的账号和密码
  email: admin@admin.com
  password: 123456

proxy:
  #与porxy交互的密码，也是各种token的私钥
  authPassword: ''
  subscriptionTemplate: /subscribe/%s?target=%s&type=%s&timestamp=%s&token=%s

email:
  #stmp地址
  host:
  #用户名称
  userName:
  #密码
  password:
  #端口
  port:
  #默认false ,邮件不支持startTls不要开启
  startTlsEnabled: false

  exceedConnections: 你当前的连接数已经超过账号最大限制，当前风险系统自动降低你一半的连接数，并且持续一个小时;如果你在一个小时后，不在触发监控指标，你的账号连接数将恢复。
  vCodeTemplate: '你的验证码为: %s,请在10分钟内使用'
  overdueDate: 你的账号即将于：%s 过期，请留意续费。

logging:
  level:
    root: info
  file:
    name: ./logs/admin.log
  logback:
    rollingpolicy:
      max-history: 7

server:
  port: 9091
  #  content-path: /api
  tomcat:
    threads:
      max: 3
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:./admin.db
    username: ''
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.jhl.admin.util.SQLiteDialect
        enable_lazy_load_no_trans: true
        format_sql: ''
        show_sql: false

#custom:
#  myExternalServers:
#    - 'socks://OjEyNy4wLjAuMToxMDgx#CORE'
#    - 'vmess://eyJhZGQiOiJ3b3JsZC5mdW45MC5jb20iLCJhaWQiOiI2NCIsImhvc3QiOiJ3b3JsZC5mdW4'
#    - 'vmess://eyJhZGQiOiJmcmVlZG9tLmpvaG5zdG9uLndhbmciLCJhaWQiOiI2NCIsImhvc3QiOiJmcmV'
#  externalServers:
#    - 'vmess://eyJhZGQiOiJmcmVlZG9tLmpvaG5zdG9uLndhbmciLCJhaWQiOiI2NCIsImhvc3QiOiJmcmV'

client:
  supported:
    - clash
    - clash2
    - clash3
    - quanx
    - surge
    - loon
    - shadowrocket

rules-source:
  url-map: {
    "Direct": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/direct.txt",
    "CnCidr": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/cncidr.txt",
    "Private": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/private.txt",
    "Tld-not-cn": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/tld-not-cn.txt",
    "Gfw": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt",
    "Greatfire": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/greatfire.txt",
    "Proxy": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/proxy.txt",
    "Apple": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/apple.txt",
    "iCloud": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/icloud.txt",
    "TelegramCidr": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/telegramcidr.txt",
    "Reject": "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/reject.txt",
    "AdvertisingLite": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingLite/AdvertisingLite_Resolve.list",
    "AdvertisingLiteDomain": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingLite/AdvertisingLite_Domain.list",
    "BanProgramAD": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list",
    "Google": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google_Resolve.list",
    "Microsoft": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list",
    "PayPal": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PayPal/PayPal.list",
    "YouTube": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube_Resolve.list"
  }